#!/bin/bash

ES_HOST=$1
ES_PORT=$2

mkdir -p esdata

for month in 2020-09 2020-10 2020-11 2020-12 2021-01 2021-02 2021-03 2021-04 2021-05 2021-06 2021-07 2021-08 2021-09 2021-10; do
    echo       "http://${ES_HOST}:${ES_PORT}/dsa-pbench.v4.run.${month}"'/pbench-run-toc-entry/_search?q=_parent:dd3423e34d629c1c230ffd983a46458b&size=10000&pretty=true'
    curl -XGET "http://${ES_HOST}:${ES_PORT}/dsa-pbench.v4.run.${month}"'/pbench-run-toc-entry/_search?q=_parent:dd3423e34d629c1c230ffd983a46458b&size=10000&pretty=true' > esdata/pbench_run_toc_data_${month}.json
done
