/* TOAST */
export const SHOW_TOAST = "SHOW_TOAST";
export const CLEAR_TOAST = "CLEAR_TOAST";

/* LOADING */
export const LOADING = "LOADING";
export const COMPLETED = "COMPLETED";
export const NETWORK_ERROR = "NETWORK_ERROR";

/*USER AUTHENTICATION */
export const KEEP_USER_LOGGED_IN = "KEEP_USER_LOGGED_IN";
export const USER_NOTION_ALERTS = "USER_NOTION_ALERTS";
export const SET_LOGIN_BUTTON = "SET_LOGIN_BUTTON";
export const SET_SIGNUP_BUTTON = "SET_SIGNUP_BUTTON";

/* NAVBAR OPEN/CLOSE */
export const NAVBAR_OPEN="NAVBAR_OPEN";
export const NAVBAR_CLOSE="NAVBAR_CLOSE";
