/* ENDPOINTS */
export const SET_ENDPOINTS = "SET_ENDPOINTS";

/* TOAST */
export const SHOW_TOAST = "SHOW_TOAST";
export const CLEAR_TOAST = "CLEAR_TOAST";
export const SHOW_FAILURE_TOAST = "SHOW_FAILURE_TOAST";

/* LOADING */
export const LOADING = "LOADING";
export const COMPLETED = "COMPLETED";
export const NETWORK_ERROR = "NETWORK_ERROR";

/* USER AUTHENTICATION */
export const KEEP_USER_LOGGED_IN = "KEEP_USER_LOGGED_IN";
export const USER_NOTION_ALERTS = "USER_NOTION_ALERTS";
export const SET_LOGIN_BUTTON = "SET_LOGIN_BUTTON";
export const SET_SIGNUP_BUTTON = "SET_SIGNUP_BUTTON";

/* NAVBAR OPEN/CLOSE */
export const NAVBAR_OPEN = "NAVBAR_OPEN";
export const NAVBAR_CLOSE = "NAVBAR_CLOSE";

/* PUBLIC DATASETS */
export const GET_PUBLIC_DATASETS = "GET_PUBLIC_DATASETS";
export const FAVORITED_DATASETS = "GET_FAVORITE_DATASETS";
export const UPDATE_PUBLIC_DATASETS = "UPDATE_PUBLIC_DATASETS";
export const SET_LOGIN_DETAILS = "SET_LOGIN_DETAILS";

/* USER DETAILS */
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const RESET_DATA = "RESET_DATA";
export const SET_USER_DETAILS = "SET_USER_DETAILS";

/* DASHBOARD OVERVIEW */
export const USER_RUNS = "USER_RUNS";
export const SAVED_RUNS = "SAVED_RUNS";
export const NEW_RUNS = "NEW_RUNS";
export const INIT_NEW_RUNS = "INIT_NEW_RUNS";
export const SELECTED_NEW_RUNS = "SELECTED_NEW_RUNS";
