/* ENDPOINTS */
export const SET_ENDPOINTS = "SET_ENDPOINTS";
export const SET_KEYCLOAK = "SET_KEYCLOAK";

/* TOAST */
export const SHOW_TOAST = "SHOW_TOAST";
export const CLEAR_TOAST = "CLEAR_TOAST";
export const SHOW_FAILURE_TOAST = "SHOW_FAILURE_TOAST";

/* LOADING */
export const LOADING = "LOADING";
export const COMPLETED = "COMPLETED";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const OPENID_ERROR = "OPENID_ERROR";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";

/* USER AUTHENTICATION */
export const USER_NOTION_ALERTS = "USER_NOTION_ALERTS";

/* NAVBAR OPEN/CLOSE */
export const NAVBAR_OPEN = "NAVBAR_OPEN";
export const NAVBAR_CLOSE = "NAVBAR_CLOSE";

/* PUBLIC DATASETS */
export const UPDATE_PUBLIC_DATASETS = "UPDATE_PUBLIC_DATASETS";
export const FAVORITED_DATASETS = "GET_FAVORITE_DATASETS";
export const SET_RESULT_OFFSET = "SET_RESULT_OFFSET";
export const SET_PAGE_LIMIT = "SET_PAGE_LIMIT";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const SET_SEARCH_KEY = "SET_SEARCH_KEY";
export const SET_PER_PAGE = "SET_PER_PAGE";

/* DASHBOARD OVERVIEW */
export const USER_RUNS = "USER_RUNS";
export const SAVED_RUNS = "SAVED_RUNS";
export const NEW_RUNS = "NEW_RUNS";
export const INIT_NEW_RUNS = "INIT_NEW_RUNS";
export const INIT_SAVED_RUNS = "INIT_SAVED_RUNS";
export const INIT_EXPIRING_RUNS = "INIT_EXPIRING_RUNS";
export const SELECTED_NEW_RUNS = "SELECTED_NEW_RUNS";
export const EXPIRING_RUNS = "EXPIRING_RUNS";
export const SET_DASHBOARD_LOADING = "SET_DASHBOARD_LOADING";
export const SET_LOADING_FLAG = "SET_LOADING_FLAG";
export const SELECTED_SAVED_RUNS = "SELECTED_SAVED_RUNS";
export const TOGGLE_RELAY_MODAL = "TOGGLE_RELAY_MODAL";
export const SET_RELAY_DATA = "SET_RELAY_DATA";
export const SET_METADATA_MODAL = "SET_METADATA_MODAL";
export const SET_TREE_DATA = "SET_TREE_DATA";
export const SET_METADATA_CHECKED_KEYS = "SET_METADATA_CHECKED_KEYS";

/* TABLE OF CONTENT */
export const GET_TOC_DATA = "GET_TOC_DATA";
export const GET_SUB_DIR_DATA = "GET_SUB_DIR_DATA";
export const UPDATE_TABLE_DATA = "UPDATE_TABLE_DATA";
export const UPDATE_SEARCH_SPACE = "UPDATE_SEARCH_SPACE";
export const UPDATE_STACK = "UPDATE_STACK";
export const UPDATE_CURR_DATA = "UPDATE_CURR_DATA";
export const UPDATE_CONTENT_DATA = "UPDATE_CONTENT_DATA";

/* SIDEBAR */
export const SET_ACTIVE_MENU_ITEM = "SET_ACTIVE_MENU_ITEM";

/* KEY MANAGEMENT */
export const SET_API_KEY_LIST = "SET_API_KEY_LIST";
export const TOGGLE_NEW_KEY_MODAL = "TOGGLE_NEW_KEY_MODAL";
export const SET_NEW_KEY_LABEL = "SET_NEW_KEY_LABEL";

/* QUISBY CHART */
export const SET_QUISBY_DATA = "SET_QUISBY_DATA";
export const SET_PARSED_DATA = "SET_PARSED_DATA";
export const SET_ACTIVE_RESOURCEID = "SET_ACTIVE_RESOURCEID";
export const IS_UNSUPPORTED_TYPE = "IS_UNSUPPORTED_TYPE";
export const TOGGLE_COMPARE_SWITCH = "TOGGLE_COMPARE_SWITCH";
export const SET_SELECTED_RESOURCE_ID = "SET_SELECTED_RESOURCE_ID";
export const UNMATCHED_BENCHMARK_TYPES = "UNMATCHED_BENCHMARK_TYPES";
export const SET_CHART_MODAL = "SET_CHART_MODAL";
export const SET_CURRENT_CHARTID = "SET_CURRENT_CHARTID";
export const SET_COMPARE_DATA = "SET_COMPARE_DATA";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
