#!/usr/bin/env python3

# See https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script

import git

repo = git.Repo(search_parent_directories=True)
hexsha = repo.head.object.hexsha
short_sha = repo.git.rev_parse(hexsha, short=True)
print(short_sha)
