---
- name: "make sure rsync is installed"
  package:
    name: rsync
    state: latest

# This needs passwordless login (as root) from a node to *itself* (*not* localhost)
- name: "copy the web-server bits to the <pbench>/public_html/static dir"
  delegate_to: "{{ inventory_hostname }}"
  synchronize:
    src: "{{ pbench_server_install_dir }}/html/static/"
    dest: "{{ pbench_dir }}/public_html/static"
    recursive: yes

