---
- name: install the EPEL repo
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: latest
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
