

* Miscellaneous scripts

These scripts are used by the RPMization code in various subdirectories
of pbench. They are made into a separate RPM package that has to be
installed if one wants to *build* RPMs (pbench, configtools, benchmarks)

- bin/mock-copy: copy RPMS out of the mock chroot environments into ~/rpmbuild/RPMS
  in preparation to pushing them to the RPM repo.
- bin/set-version-release: modify the spec file with the correct version (usually
  obtained from a config file) and seqno (obtained from =./seqno=).
- bin/get-inc.py: read current seqno, increment and write updated seqno, return current seqno.
- mk/rpm.mk: generic makefile using the above scripts. It is included by the various
  rpm Makefiles.
 

The rpm Makefiles include rpm.mk either from its installed location (/opt/misc-scripts/mk/rpm.mk)
or from its relative location in the pbench git repo structure (../misc-scripts/mk/rpm.mk).
That should allow one the flexibility to have misc-scripts installed or not.

* Dependencies

misc-scripts < configtools < pbench, fio etc.
