#!/bin/bash

# This script is the entrypoint for the Agent containers.
#
# Since execution in these environments does not follow the normal login path,
# we first execute the `agent/profile` script to set up the environment for
# Agent commands.  Then we exec the requested command.

source /opt/pbench-agent/profile

if [[ -z "${*}" ]]; then
  echo "No command supplied" >&2
  exit 127
fi

# If the exec is successful, control won't return to this script, so the
# commands following it are only for reporting the error (so disable the
# lint check).
# shellcheck disable=SC2093
exec "${@}"
rc=${?}
echo "exec ${@} failed with status ${rc}"
exit ${rc}
