# {{ distro }} pbench-agent-tool-meister image
FROM pbench-agent-tools-{{ distro }}:{{ tag }}

COPY ./jaeger/bin/jaeger-agent /usr/bin/

# Port 9400 should be the optional dcgm tool, 9100 the optional node_exporter
# tool, and 55677 the pcp (pmcd) tool.
EXPOSE 9100 9400 55677
ENTRYPOINT [ "/opt/pbench-agent/util-scripts/tool-meister/tool-meister-ep" ]
