# {{ distro_image_name }} pbench-agent base image
FROM docker.io/library/{{ distro_image }}

# Install the appropriate pbench repository file for {{ distro_image_name }}.
COPY ./{{ pbench_repo_file }} /etc/yum.repos.d/pbench.repo

# Install the pbench-agent RPM, which should have all its dependencies enumerated;
# ... and make sure we have a proper pbench-agent.cfg file in place;
# ... and finally, ensure the proper pbench-agent environment variables are set up.
RUN \
{% if distro_image == 'centos:8' %}
    {{ pkgmgr }} module -y enable python36 && \
    {{ pkgmgr }} module -y disable python38 && \
{% endif %}
{% if distro_image.startswith('centos') %}
    {{ pkgmgr }} install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ distro_image.split(':', 1)[1] }}.noarch.rpm && \
{% endif %}
    {{ pkgmgr }} install -y {% if distro_image == 'centos:8' %}--enablerepo PowerTools {% endif %} pbench-agent && \
    {{ pkgmgr }} -y clean all && \
    rm -rf /var/cache/{{ pkgmgr }}
