# {{ distro }} pbench-agent {{ kind }} image
FROM pbench-agent-base-{{ distro }}:{{ tag }}

# Install all the RPMs required for this image.
#
# FIXME: this is not exhaustive, it does not include RPMs to support
#        Kubernetes or RHV environments.
RUN {% if distro == 'centos-7' %}yum{% else %}dnf{% endif %} install -y {% if distro == 'centos-8' %}--enablerepo powertools {% endif %}{{ rpms }} && \
    {% if distro == 'centos-7' %}yum{% else %}dnf{% endif %} -y clean all && \
    rm -rf /var/cache/{% if distro == 'centos-7' %}yum{% else %}dnf{% endif %}
