# {{ distro }} pbench-agent-tool-data-sink  image
FROM pbench-agent-tools-{{ distro }}:{{ tag }}

VOLUME /var/lib/pbench-agent

# Port 8080 should be Bottle server, 9090 optional Prometheus server, and 44566
# the optional pmproxy server.
EXPOSE 8080 9090 44566
ENTRYPOINT [ "/opt/pbench-agent/util-scripts/tool-meister/tool-data-sink-ep" ]
