#!/bin/bash

url_prefix="${1}"
dist="${2}"
arch="${3}"

if [[ "${dist}" == "centos-8" ]]; then
    dist="epel-8"
elif [[ "${dist}" == "centos-7" ]]; then
    dist="epel-7"
fi

version_string="$(yum list -q --repofrompath pbench,"${url_prefix}/pbench/${dist}-${arch}" pbench-agent.noarch 2>/dev/null | awk 'FNR==2{print $2}')"
if [[ -z "${version_string}" ]]; then
    printf -- "Failed to fetch pbench-agent.noarch version string from '%s/pbench/%s-%s'\n" "${url_prefix}" "${dist}" "${arch}" >&2
    exit 1
fi
# 0.69.3-1
ver="${version_string%g*}"
major="${ver%%.*}"
major_minor="${ver%.*}"
commit_id="${version_string#*g}"
printf -- "%s v%s v%s-latest v%s-latest\n" "${commit_id}" "${ver}" "${major}" "${major_minor}"
exit 0
