---
skip_list:
  - experimental        # all rules tagged as experimental
  - no-changed-when     # Commands should not change things if nothing needs doing.
  - package-latest      # Do not complain about using `latest'
