---
- name: install pbench-agent
  hosts: servers
  remote_user: root
  become: yes
  become_user: root

  vars:
    package_state: "latest"

  roles:
    - include-vars
    - pbench-repo-install
    - pbench-agent-install
    - pbench-agent-config-install
    - pbench-agent-key-install

