---
- name: install pbench-agent config and key files
  hosts: servers
  become: yes
  become_user: root

  # The default value ('production') can be overridden by cenv, a host-specific
  # inventory variable.
  vars:
    pbench_configuration_environment: "{{ cenv | default('production') }}"

  roles:
    - pbench_agent_config
