---
- name: install pbench-agent
  hosts: servers
  remote_user: root
  become: yes
  become_user: root

  vars:
    pbench_configuration_environment: "{{ cenv | default('production') }}"
    package_state: "latest"

  roles:
    - pbench-repo-install
    - pbench-agent-install
    - pbench-agent-config-install
    - pbench-agent-key-install

