---
distro: "{{ 'epel' if ansible_distribution == 'RedHat'
          else
            'fedora' if ansible_distribution == 'Fedora'
          else
            '' }}"
distrodir: "{{ distro }}-{{ ansible_distribution_major_version }}-$basearch"
