#!/bin/bash

image_repo="${1}"
distro="${2}"
githash="$(grep -v -E "^v" ${distro}-tags.lis)"
ver="$(grep -E "^v" ${distro}-tags.lis | grep -v latest)"

if [[ "${3}" == "_major" ]]; then
    other="$(grep -E "^v" ${distro}-tags.lis | grep latest | awk '{print $1}')"
elif [[ "${3}" == "_minor" ]]; then
    other="$(grep -E "^v" ${distro}-tags.lis | grep latest | awk '{print $2}')"
else
    other="${3}"
fi

function pushit {
    buildah push ${1} ${image_repo}/${1}
}

for image in base tools workloads all; do
    pushit pbench-server-${image}-${distro}:${githash}
    pushit pbench-server-${image}-${distro}:${ver}
    if [[ ! -z "${other}" ]]; then
        pushit pbench-server-${image}-${distro}:${other}
    fi
done
