---
- name: disable pbench-server
  hosts: servers
  remote_user: pbench

  vars:
    pbench_configuration_environment: "{{ cenv | default('production') }}"

  roles:
    - pbench-server-vars
    - pbench-server-crontab-disable
