---
- name: install pbench-server
  hosts: servers
  remote_user: root
  become: yes
  become_user: root

  vars:
    package_state: "latest"
    apache_options: "+Indexes +FollowSymLinks"

  roles:
    - pbench-repo-install
    - pbench-server-install
    - pbench-server-config
