#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys, csv, json, warnings, logging

input_file = sys.argv[1]
output_file = sys.argv[2]
metrics = []

in_file = open(input_file, "r")
metrics_datalog = in_file.readlines()
with open(output_file, 'w') as f:
    for item in metrics_datalog:
        values = []
        try:
            item = json.loads(item)
        except ValueError:
            logging.warn("not a valid json document, skipping the entry")
            continue
        values = item['metrics']
        if len(values) == 1:
            item[item['name']] = values[0].values()[0]
            del item['name']
            del item['metrics']
            metrics.append(item)
        elif len(values) > 1:
            for i in values:
                add_metric = {}
                add_metric[item['name']] = i
                add_metric['@timestamp'] = item['@timestamp']
                add_metric['type'] = item['type']
                if "type" in add_metric[item['name']]['labels']:
                    val = add_metric[item['name']]['labels']['type']
                    if "*" in add_metric[item['name']]['labels']['type']:
                        add_metric[item['name']]['labels']['type'] = val.split("*")[1]
                    if "[]" in add_metric[item['name']]['labels']['type']:
                        add_metric[item['name']]['labels']['type'] = val.split("[]")[1]
                metrics.append(add_metric)
        else:
            logging.warn("metric doesn't have a value")
    json.dump(metrics, f, sort_keys=True, indent=4, separators=(',', ':'))
