---
# activate the server - create results dir structure

# The sefcontext module is available from Galaxy with:
#
#    ansible-galaxy collection install community.general
#
# We have two tasks to set the SELinux context with semanage on the top level
# directory (typically /pbench or /srv/pbench) and its subdirectories: they get
# a default_t type.  We then override the type for the `public_html' subdirs
# (and their subdirs) which must be available through HTTP: they get a
# httpd_sys_content_t type.

# The rest of the tasks create the directory structure under the top-level
# directory. Then at the end, we run a restorecon to give every directory its
# proper label.

- name: add semanage fcontexts - top level dir gets default_t and subdirs inherit
  community.general.sefcontext:
    target: "{{ pbench_dir }}(/.*)?"
    setype: default_t
    state: present

- name: add semanage fcontexts - public_html gets httpd_sys_content_t
  community.general.sefcontext:
    target: "{{ pbench_dir }}/{{ item}}(/.*)?"
    setype: httpd_sys_content_t
    state: present
  with_items:
    - public_html

- name: ensure top level dir is present with default_t type
  file:
    path: "{{ pbench_dir }}"
    owner: "{{ pbench_user }}"
    group: "{{ pbench_group }}"
    mode:  0775
    state: directory

- name: ensure public_html directories and top-level subdirs are present
  file:
    path: "{{ pbench_dir }}/{{ item }}"
    owner: "{{ pbench_user }}"
    group: "{{ pbench_group }}"
    mode:  0775
    state: directory
  with_items:
    - public_html
    - public_html/incoming
    - public_html/results
    - public_html/users
    - public_html/static

- name: ensure log directory is present
  file:
    path: "{{ pbench_logs_dir }}"
    owner: "{{ pbench_user }}"
    group: "{{ pbench_group }}"
    mode:  0775
    state: directory

- name: ensure tmp directory is present
  file:
    path: "{{ pbench_tmp_dir }}"
    owner: "{{ pbench_user }}"
    group: "{{ pbench_group }}"
    mode: 0775
    state: directory

- name: ensure quarantine directory is present
  file:
    path: "{{ pbench_quarantine_dir }}"
    owner: "{{ pbench_user }}"
    group: "{{ pbench_group }}"
    mode: 0775
    state: directory

- name: ensure reception areas and quarantine areas are present
  file:
    path: "{{ pbench_reception_dir_prefix }}-{{ item }}"
    owner: "{{ pbench_user }}"
    group: "{{ pbench_group }}"
    mode:  0775
    state: directory
  with_items:
    - "002"

- name: Apply new SELinux file context to filesystem
  command:
    cmd: "restorecon -iv {{ pbench_dir }}/{{ item }}"
  with_items:
    - ""
    - public_html
    - public_html/incoming
    - public_html/results
    - public_html/users
    - public_html/static
