#!/usr/bin/perl
#

use strict;
use warnings;

my $pbench_lib_path;
BEGIN {
	$pbench_lib_path = `getconf.py pbench_install_dir pbench-agent`;
	chomp $pbench_lib_path;
	$pbench_lib_path .= "/lib";
}

use lib "$pbench_lib_path";
use JSON;
use File::Basename;
use Data::Dumper;
use PbenchAnsible qw(ssh_hosts);

my @hosts = @ARGV;
my $output = ssh_hosts(\@hosts, "/bin/ls", "/tmp", "/tmp");
print "output is:\n$output\n";
