#! /bin/bash

# mock out the output of pminfo

case $1 in
     -a)
         shift 2
         ;;
     *)
         exit 1
         ;;
esac

if [ -z "$1" ] ;then
    html_page=""
else
    html_page=$1
fi

html_pages='
disk.all.read
disk.all.write
mem.util.free
mem.util.bufmem
swap.pagesin
swap.pagesout
'

if [ -z "$html_page" ] ;then
    echo $html_pages | sed 's/ /\
/g'
else
    echo $html_pages | sed 's/ /\
/g' | grep "^$html_page"

fi
exit 0
