#! /bin/bash

# mock out the output of pminfo

case $1 in
     -a)
         shift 2
         ;;
     *)
         exit 1
         ;;
esac

if [ -z "$1" ] ;then
    html_page=""
else
    html_page=$1
fi


html_pages='
disk.all.read
disk.all.write
disk.all.blkread
disk.all.blkwrite
disk.all.total
disk.all.read_bytes
disk.all.write_bytes
disk.all.total_bytes
disk.all.avactive
mem.util.free
mem.util.bufmem
mem.util.cached
swap.pagesin
swap.pagesout
swap.in
swap.out
swap.used
network.interface.in.bytes
network.interface.in.packets
network.interface.in.errors
network.interface.out.bytes
network.interface.out.packets
network.interface.out.errors
network.interface.collisions
filesys.capacity
filesys.mountdir
filesys.blocksize
pmda.uname
kernel.all.intr
kernel.all.pswitch
kernel.all.cpu.user
kernel.all.cpu.nice
kernel.all.cpu.sys
kernel.all.cpu.idle
kernel.all.cpu.intr
kernel.all.cpu.wait.total
kernel.all.cpu.irq.soft
kernel.all.cpu.irq.hard
kernel.all.cpu.steal
kernel.all.cpu.guest
kernel.all.cpu.vuser
kernel.all.cpu.guest_nice
kernel.all.cpu.vnice
kernel.all.load
kernel.all.nusers
kernel.all.uptime
kernel.uname.release
kernel.uname.version
kernel.uname.sysname
kernel.uname.machine
kernel.uname.nodename
kernel.uname.distro
hinv.nnode
hinv.ncpu
hinv.ndisk
hinv.physmem
hinv.pagesize
hinv.hugepagesize
hinv.ninterface
hinv.nfilesys
hinv.machine
hinv.map.scsi
hinv.map.cpu_num
hinv.map.cpu_node
hinv.map.dmname
hinv.cpu.clock
hinv.cpu.vendor
hinv.cpu.model
hinv.cpu.stepping
hinv.cpu.cache
hinv.cpu.bogomips
hinv.cpu.model_name
hinv.cpu.flags
hinv.cpu.cache_alignment
hinv.cpu.online
hinv.node.online
pmcd.numagents
pmcd.numclients
pmcd.version
pmcd.services
pmcd.build
pmcd.agent.status
pmcd.pmlogger.pmcd_host
pmcd.pmlogger.archive
pmcd.pmlogger.port
pmcd.pmlogger.host
event.flags
event.missed
'

if [ -z "$html_page" ] ;then
    echo $html_pages | sed 's/ /\
/g'
else
    echo $html_pages | sed 's/ /\
/g' | grep "^$html_page"

fi
exit 0

