#!/bin/bash

echo "$(basename ${0}) ${@}" >> ${_testlog}

if [[ "${1}" == "get" ]]; then
    echo "get ${2} output ..."
    case "${2}" in
        nodes|ev)
            echo "${2} done."
            ;;
        --raw)
            echo "get ${2} done."
            ;;
        pod)
            printf -- "non-router-pod-A\nrouter-pod-A\nnon-router-pod-B\nrouter-pod-B\nrouter-pod-C\n"
            ;;
        *)
            if [[ -x /bin/sleep ]]; then
                /bin/sleep 120
            else
                /usr/bin/sleep 120
            fi
            echo "${2} slept a long time!"
            ;;
    esac
    exit 0
elif [[ "${1}" == "exec" ]]; then
    exit 0
elif [[ "${1}" == "logs" ]]; then
    exit 0
fi

exit 1
