---
# Install config file for pbench agent or server (the inventory file
# specifies which through the configurl variable). Other variables
# are specified in the default vars of this role, but can be overridden
# (if necessary) by specifying them in the inventory file.

- name: install the config file
  get_url:
        url: "{{ configurl }}"
        dest: "{{ pbench_server_config_dest }}"
        mode: 0444
        owner: "{{ pbench_owner }}"
        group: "{{ pbench_group }}"

