---
# pbench agent configuration
- name: "pbench agent configuration - open firewall ports for tool meister"
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    offline: true
    state: enabled
  with_items:
    - "{{ pbench_redis_port }}"
    - "{{ pbench_wsgi_port }}"
