#!/bin/bash

script_path=`dirname $0`
pbench_bin="`cd ${script_path}/..; /bin/pwd`"

# source the base script
. "$pbench_bin"/base

if [ -d "$pbench_run" ]; then
	log "Cleaning up $pbench_run"
	pushd "$pbench_run" && rm -rf * && popd
fi
