#! /usr/bin/env python2

# Usage: pbench-add-metalog-option <options.file> <metadata log file> <option>

# Add an option to the [pbench] section of the metadata.log file.
# E.g. using an 'iterations' arg for the option
#
# iterations: 1-iter, 2-iter, 3-iter
#
# where the iterations are in the <iterations.file>, one iteration per line.

import sys
try:
    # python3
    from configparser import SafeConfigParser
except:
    from ConfigParser import SafeConfigParser

def main(ifile, lfile, section):
   config = SafeConfigParser()
   config.read(lfile)
   # python3
   # config['pbench']['iterations'] = ', '.join(open(ifile).read().split())
   config.set('pbench', section, ', '.join(open(ifile).read().split()))
   config.write(open(lfile, "w"))
   
if __name__ == '__main__':
   ifile = sys.argv[1]
   lfile = sys.argv[2]
   section = sys.argv[3]
   status = main(ifile, lfile, section)
   sys.exit(status)
   
