#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; sh-indent-for-case-alt: + -*-

script_path=`dirname $0`
script_name=`basename $0`
pbench_bin="`cd ${script_path}/..; /bin/pwd`"

# source the base script
. "$pbench_bin"/base

# The sole purpose of this script is to ensure a tool
# of your choosing is used during the execution of a benchmark.
# For a list of performance tools, look at the
# $pbench_bin/tool-scripts directory.

# Defaults
toolset="default"
remote=""
label=""
group=""
default_interval=$(getconf.py interval pbench/tools)
if [[ -z "${default_interval}" ]] ;then
	default_interval=3
fi

function usage() {
	printf "usage:\n"
	printf "$script_name --toolset=<tool-set> [--group=<group-name>] [--remote=<remote-host>] [--label=<label>] [--interval=<interval] -- [all tool specific options here]\n"
}

# Process options and arguments
opts=$(getopt -q -o hr:l:g:i: --longoptions "help,toolset:,remote:,label:,group:,interval:" -n "getopt.sh" -- "$@");
if [ $? -ne 0 ]; then
	printf "\n"
	printf "%s\n" $*
	printf "$script_name: you specified an invalid option or forgot a required option value\n\n"
	usage
	exit 1
fi
eval set -- "$opts";
while true; do
	case "$1" in
		--toolset)
		shift;
		if [ -n "$1" ]; then
			toolset="$1"
			shift;
		fi
		;;
		-r|--remote)
		shift;
		if [ -n "$1" ]; then
			remote="--remote=$1"
			shift;
		fi
		;;
		-l|--label)
		shift;
		if [ -n "$1" ]; then
			label="--label=$1"
			shift;
		fi
		;;
		-g|--group)
		shift;
		if [ -n "$1" ]; then
			group="--group=$1"
			shift;
		fi
		;;
		-i|--interval)
		shift;
		if [ -n "$1" ]; then
			default_interval="$1"
			shift;
		fi
		;;
		-h|--help)
		usage;
		exit 0
		;;
		--)
		shift;
		break;
		;;
	esac
done

typeset -i nerrs=0
case "$toolset" in
	default)
	default_tool_set=$(getconf.py -l default-tool-set pbench/tools)
	for tool_name in $default_tool_set; do
		if [[ ${tool_name} == "perf" ]]; then
			# Ignore, we'll register it after all the others
			# FIXME: Why is perf always registered?
			continue
		fi
		interval=$(getconf.py interval tools/${tool_name})
		if [ -z "${interval}" ] ;then
			interval=${default_interval}
		fi
		pbench-register-tool --name=${tool_name} $remote $label $group -- --interval="$interval"
		rc=$?
		if [ $rc != 0 ] ;then
			nerrs=$nerrs+1
		fi
	done
	# low overhead perf
	# FIXME: Why is perf always registered?
	pbench-register-tool --name=perf $remote $label $group -- --record-opts="record -a --freq=100"
	rc=$?
	if [ $rc != 0 ] ;then
		nerrs=$nerrs+1
	fi
	;;
esac

exit $nerrs
