#!/usr/bin/env python3
# -*- mode: python -*-

"""
Simple command-line wrapper to shut down the tool meister environment.
"""

import sys

from pbench.agent.tool_meister_stop import main

if __name__ == "__main__":
    sys.exit(main())
