#!/usr/bin/env python3
# -*- mode: python -*-

"""
Simple command-line wrapper to shut down the tool meister environment.
"""

import sys

from pbench.agent.tool_meister_stop import main


sys.exit(main())
