#!/bin/bash

# just find tools in $sample_dir and call tool-specific CDM post-processing script

period_doc=$1
es_dir=$2
sample_dir=$3

for tools_dir in `/bin/ls $sample_dir | grep "^tools-"`; do
	for host in `/bin/ls $sample_dir/$tools_dir`; do
		mkdir -p $es_dir/metrics/$host
		for tool in `/bin/ls $sample_dir/$tools_dir/$host`; do
			if [ -e /opt/pbench-agent/tool-scripts/postprocess/${tool}-postprocess-cdm ]; then
				cmd="/opt/pbench-agent/tool-scripts/postprocess/${tool}-postprocess-cdm $sample_dir/$tools_dir/$host/$tool $period_doc $es_dir $host"
				echo $cmd
				$cmd
			fi
		done
	done
done
