#!/bin/bash

script_path=`dirname $0`
script_name=`basename $0`
pbench_bin="`cd ${script_path}/..; /bin/pwd`"

# source the base script
. "$pbench_bin"/base

# The sole purpose of this script is to ensure a tool
# of your choosing is used during the execution of a benchmark.
# For a list of performance tools, look at the
# $pbench_bin/tool-scripts directory.

# Defaults
group=default
start_trigger=""
stop_trigger=""

function usage() {
	printf "usage:\n"
	printf "${script_name} --group=<tool group> --start-trigger=<string to match> --stop-trigger=<string to match>"
}

# Process options and arguments
opts=$(pbench-argparse -q -o h --longoptions "help,group:,start-trigger:,stop-trigger:" -n "${script_name}" -- "${@}")
sts=${?}
if [[ ${sts} -ne 0 ]]; then
	printf -- "\n" >&2
	usage >&2
	exit ${sts}
fi

eval set -- "${opts}"
while true; do
	opt=${1}
	shift
	case "${opt}" in
	--start-trigger)
		if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for --start-trigger\n" >&2; exit 100; fi
		start_trigger="$1"
		shift
		;;
	--stop-trigger)
		if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for --stop-trigger\n" >&2; exit 100; fi
		stop_trigger="$1"
		shift
		;;
	--group)
		if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for --group\n" >&2; exit 100; fi
		group="$1"
		shift
		;;
	-h|--help)
                usage
                exit 0
                ;;
	--)
		break
		;;
	*)
		printf "\n${script_name}: you specified an invalid option or provided an unexpected argument\n\n" >&2
		usage >&2
		exit 1
		;;
	esac
done

if [ "$start_trigger" != "${start_trigger%%:*}" ]; then
	printf "$script_name: the start trigger cannot have a colon in it: \"${start_trigger}\"\n"
	exit 1
fi
if [ "$stop_trigger" != "${stop_trigger%%:*}" ]; then
	printf "$script_name: the stop trigger cannot have a colon in it: \"${stop_trigger}\"\n"
	exit 1
fi

if [ ! -f "$pbench_run/tool-triggers" ]; then
	mkdir -p "$pbench_run"
	echo "#group:start-trigger:stop-trigger" > "$pbench_run/tool-triggers"
fi
# remove any previous trigger for the given group
sed -i /^$group.*/d "$pbench_run/tool-triggers"
# remember this trigger
printf "%s:%s:%s\n" "$group" "$start_trigger" "$stop_trigger" >> "$pbench_run/tool-triggers"
printf "tool trigger strings for start: \"$start_trigger\" and for stop: \"$stop_trigger\" are now registered for tool group: $group\n"
