#!/usr/bin/env python3
# -*- mode: python -*-

"""
Simple command-line wrapper to launch the tool meister environment.
"""

import sys

from pbench.agent.tool_meister_start import main


if __name__ == "__main__":
    sys.exit(main())
