#!/usr/bin/env python3

# Usage: pbench-add-metalog-option <metadata log file> <section> <option>

# Add an option to a section of the metadata.log file.
# E.g. using an 'iterations' arg for the option
#
# iterations: 1-iter, 2-iter, 3-iter
#
# where the iterations are in the <iterations.file>, one iteration per line.

import sys
from configparser import NoSectionError

from pbench.common import MetadataLog


def main(lfile, section, option):
    mdlog = MetadataLog()
    mdlog.read(lfile)
    sin = sys.stdin.read()
    try:
        mdlog.set(section, option, ", ".join(sin.split()))
    except NoSectionError:
        mdlog.add_section(section)
        mdlog.set(section, option, ", ".join(sin.split()))
    mdlog.write(open(lfile, "w"))


if __name__ == "__main__":
    lfile = sys.argv[1]
    section = sys.argv[2]
    option = sys.argv[3]
    status = main(lfile, section, option)
    sys.exit(status)
