#!/usr/bin/env python3
# -*- mode: python -*-

"""pbench-tool-meister-client - CLI client interface for pbench

Responsible for publishing the requested Tool Meister action.
"""

import logging
import os
import sys

from pbench.agent.constants import (
    cli_tm_allowed_actions,
    cli_tm_channel_prefix,
    redis_port,
)
from pbench.agent.tool_meister_client import Client


def main(argv):
    """Main program for the Tool Meister client CLI.  The command line
    arguments are:

      group - the tool group on which the actions will be taken

      directory - the directory where data gathered from the actions will be
                  stored

      action - the particular action to take, can we one of "start", "stop",
               or "send" (see `cli_tm_allowed_actions`).
    """
    PROG = os.path.basename(argv[0])
    logger = logging.getLogger(PROG)

    if os.environ.get("_PBENCH_TOOL_MEISTER_CLIENT_LOG_LEVEL") == "debug":
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO
    logger.setLevel(log_level)
    sh = logging.StreamHandler()
    sh.setLevel(log_level)
    shf = logging.Formatter("%(message)s")
    sh.setFormatter(shf)
    logger.addHandler(sh)

    try:
        group = argv[1]
    except IndexError:
        raise Exception("Missing group argument")
    try:
        directory = argv[2]
    except IndexError:
        raise Exception("Missing directory argument")
    try:
        action = argv[3]
    except IndexError:
        raise Exception("Missing action argument")
    else:
        if action not in cli_tm_allowed_actions:
            raise Exception(
                f"Unrecognized action, '{action}', allowed actions are:"
                f" {cli_tm_allowed_actions}"
            )
        elif action == "kill":
            # FIXME: we need to implement the gritty method of killing all the
            # tool meisters, locally and remotely, and ensuring they are all
            # properly shut down.
            return 0

    # The Redis server is always running on the local host with the CLI.
    with Client(
        redis_host="localhost",
        redis_port=redis_port,
        channel_prefix=cli_tm_channel_prefix,
        logger=logger,
    ) as client:
        ret_val = client.publish(group, directory, action)

    return ret_val


if __name__ == "__main__":
    status = main(sys.argv)
    sys.exit(status)
