#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8 -*-

script_path=`dirname $0`
script_name=`basename $0`
pbench_bin="`cd ${script_path}/..; /bin/pwd`"

# source the base script
. "$pbench_bin"/base

# This script will stop all tools that belong
# to a specific group.  This is typically called
# by a benchmark script when some activity needs to
# monitored.

# Defaults
group=default
dir="/tmp"
iteration=1

# Process options and arguments

opts=$(getopt -q -o d:g: --longoptions "dir:,group:,iteration:" -n "getopt.sh" -- "$@");
if [ $? -ne 0 ]; then
	printf "\n"
	printf "$script_name: you specified an invalid option\n\n"
	printf "The following are required:\n\n"
	printf -- "\t-d str --dir=str, str = a directory where the $script_name\n"
	printf -- "\t                          will store and process data\n"
	printf "\n"
	printf -- "\t-g str --group=str, str = a tool group used in a benchmark\n"
	printf -- "\t                          (the default group is 'default')\n"
	printf "\n"
	printf -- "\t-i str --iteration=num, num = a number representing the\n"
	printf -- "\t                              iteration data is being\n"
	printf -- "\t                              collected for\n"
	exit 1
fi
eval set -- "$opts";
while true; do
	case "$1" in
		-g|--group)
		shift;
		if [ -n "$1" ]; then
			group="$1"
			shift;
		fi
		;;
		-d|--dir)
		shift;
		if [ -n "$1" ]; then
			dir="$1"
			shift;
		fi
		;;
		-i|--iteration)
		shift;
		if [ -n "$1" ]; then
			iteration="$1"
			shift;
		fi
		;;
		--)
		shift;
		break;
		;;
	esac
done

if [ -f "$pbench_run/tools.$group" ]; then
	groupfile="$pbench_run/tools.$group"
else
	# if there were no tools registered for the group, use the 
	# tools registered in the default group
	groupfile="$pbench_run/tools.default"
fi
if [ ! -f "$groupfile" ]; then
	error_log "[$script_name] failed to find tools group file, \"$groupfile\""
	exit 1
fi

tool_dir="$dir/tools-$group"
# this directory *should* exist already
if [ ! -d $tool_dir ]; then
	mkdir -p $tool_dir
fi

## Stop this tool
while read this_line; do
	name=`echo $this_line | awk -F: '{print $1}'`
	if [ "$name" == "label" ]; then
		continue
	fi
	if echo $name | grep -q "@"; then
		# tool is on remote host
		remote=`echo $name | cut -d\@ -f2`
		# tool options are stored on the remote host's tool file, so no need to pass it here
		cmd="ssh $ssh_opts -n $remote stop-tools --iteration=$iteration --group=$group --dir=$dir"
		debug_log "[$script_name]$cmd"
		$cmd | sed -e 's/\(.*\)/'[$remote]'\1/g'
	else
		cmd="$pbench_bin/tool-scripts/$name --stop --iteration=$iteration --group=$group --dir=$dir `grep ^$name $groupfile | cut -d: -f2- | sed -e 's/"/\\\"/g'`"
		debug_log "[$script_name]$cmd"
		cmd_dir=$tool_dir/cmds
		cmd_file=$cmd_dir/pbench-$name-stop.cmd
		mkdir -p $cmd_dir
		echo $cmd >$cmd_file
		chmod +x $cmd_file
		$cmd_file &
	fi
done <$groupfile
wait
