---
- name: "Create links in doc root to various pbench directories."
  file:
    src: "{{ pbench_dir }}/public_html/{{ item }}"
    path: "{{ httpd_document_root_dir }}/{{ item }}"
    state: link
  with_items:
    - incoming
    - results
    - users
    - static
  notify:
    - restart apache

- name: "Create pbench-tarballs link in doc root"
  file:
    src: "{{ pbench_dir }}/archive/fs-version-001"
    path: "{{ httpd_document_root_dir }}/pbench-tarballs"
    state: link
  notify:
    - restart apache

- name: "Install the pbench server proxy config file"
  template:
    src: etc/httpd/conf.d/pbench.conf.j2
    dest: /etc/httpd/conf.d/pbench.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache

- name: Allow application HTTP connections
  # command: "setsebool -P httpd_can_network_connect on"
  seboolean:
    name: httpd_can_network_connect
    persistent: yes
    state: yes

- name: "Make sure rsync is installed. Used below."
  package:
    name: rsync
    state: latest

- name: "Copy the web-server bits to the <pbench>/public_html/static directory."
  synchronize:
    src: "{{ pbench_server_install_dir }}/html/static/"
    dest: "{{ pbench_dir }}/public_html/static"
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"
