---
- name: Install pbench-agent
  hosts: servers
  remote_user: root

  # The default value ('production') can be overridden by cenv, a host-specific
  # inventory variable.
  vars:
    pbench_configuration_environment: "{{ cenv | default('production') }}"

  roles:
    - pbench_repo_install
    - pbench_agent_install
    - pbench_agent_config
