---
dependencies: []

galaxy_info:
  role_name: pbench_agent_config
  author: The Pbench team
  description: Role to configure a pbench agent installation
  license: "license(GPL-3.0-or-later)"
  min_ansible_version: 2.4
  platforms:
    - name: Fedora
      versions:
        - all
    - name: RHEL
      versions:
        - 7
        - 8
    - name: CentOS
      versions:
        - 7
        - 8
  galaxy_tags:
    - pbench
