# Created 2017-07-14 Fri 16:32
#+OPTIONS: html-link-use-abs-url:nil html-postamble:t
#+OPTIONS: html-preamble:t html-scripts:t html-style:t
#+OPTIONS: html5-fancy:nil tex:t
#+OPTIONS: ^:{} H:2
#+TITLE: PBench release notes
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+KEYWORDS: pbench
#+HTML_LINK_HOME: 
#+HTML_LINK_UP: 
#+HTML_MATHJAX: 
#+HTML_HEAD_EXTRA: 
#+SUBTITLE: 
#+INFOJS_OPT: 
#+LATEX_HEADER: 

* Version 0.44

** Installation                                                    :external:

There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install or update.

After installation or update, you should have version 0.44-1gf694c2f
of the pbench-agent RPM installed.

** agent

*** Known problems and backward incompatibilities

These are identical to v0.43 and are repeated here for convenience:

- =pbench-user-benchmark= will now produce a warning about a non-existent
  JSON result file (see below).

- =pbench-fio= issues two warnings after postprocessing the latency log
  files.  This is caused by the last two lines in two of these files
  having the same timestamp. This is probably a fio bug.

- (not fixed in v0.44) The Python Pandas package goes by different
  names on RHEL and Fedora.  The current code uses "python-pandas"
  which works for RHEL, but not for Fedora.  The workaround for Fedora
  is to actually change the =pbench-fio= script to install
  "python2-pandas". We have a work item to fix this for v0.45.

- Two new dependencies have been added to =pbench-agent=: =perl-JSON=
  and =perl-Switch=. These are used to produce JSON files for the
  results of benchmarks (currently, =pbench-uperf=, =pbench-moongen=
  and =pbench-fio= produce such JSON files). =perl-JSON= is available
  from the standard RHEL and Fedora repos, but =perl-Switch= is only
  available from the standard Fedora repos; on RHEL, you will need to
  add the RHEL "optional packages" repo. This can be done by copying

  https://github.com/redhat-performance/perf-dept/blob/master/repo_files/rhel7-latest.repo

  to =/etc/yum.repos.d=.

*** Bug fixes and enhancements

- (v0.43) pbench-user-benchmark also produces a rudimentary JSON result
  file (it only includes a duration for the run), but there are
  provisions to allow the user benchmark to produce a JSON file
  which pbench-user-benchmark will upload for indexing.

- (v0.43 with updates) Some benchmark scripts now take an additional
  option: --sysinfo=<val> where <val> can be "default", "all", "none",
  or a comma-separated list of words from the following list:
  kernel_config, block, libvirt, sos, block, topology, ara.  The <val>
  is passed through to pbench-collect-sysinfo, to allow the the user
  to tailor what kind of system information will be collected (if
  any). E.g.

  pbench-fio --sysinfo=none <other args>

  will not collect *any* system information.

  pbench-user-benchmark, pbench-fio, pbench-uperf and pbench-moongen
  have been modified to accept the new option. We may (or may not)
  get to the rest of the benchmarks in v0.45, but if you need a
  benchmark modified along these lines asap, please open an issue
  and mark it "v0.45".

- The prometheus tool now accepts some additional options: a port
  number can be specified instead of the default, as well as
  non-default certs. It also sets GOPATH properly. Note that the
  prom2json tool that is used underneath the covers has undergone
  some changes that broke functionality. Fixes were submitted upstream
  and have been merged, so things work properly now.   

  See upstream issues:

  https://github.com/prometheus/prom2json/issues/18,
  https://github.com/prometheus/prom2json/issues/20

  and associated PR:

  https://github.com/prometheus/prom2json/pull/22

  If you find any problems, please open an issue, but as far as
  we know, there should not be any.

- Various tools added to the default configuration for openshift.

- A bug in BenchPostprocess::get_uid has been fixed: it was fixed
  previously, but the fix got lost somehow. It is now fixed again,
  hopefully for good.

** server
There is a minor change in the server to make a mail message report
more accurately. This will be deployed opportunistically.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.43
:END:
There is a new RPM that should be identical to the two previous
versions. The dependencies are now handled correctly, so it should
be safe to update to v0.44 if you want.

If you do decide to update, the instructions are standard:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.44-1gf694c2f.

** Changelog
This is the list of visible (non-merge, non-unit-test-related) commits
since v0.43:

- f694c2f Version bump
- 54fba8a pidstat-postprocess: nuke commas from commands.
- 4010360 Modify installation steps of prom2json
- 24f2b9c Fix a subsitution bug in BenchPostprocess::get_uid
- aacd800 Update the subject and body message of ssh failure mail
- 6303e80 Fixes the way GOPATH is set
- 3b084b1 Parameterize certs and port for prometheus-metrics
- ceafcf0 Register tools on OpenShift infra, cns nodes
- 4a8928a Fix script to write all the metrics
- a9b066a move, clear results only when set in vars
- 9c4e24d Register prometheus-metrics tool on openshift
- 481b636 Register disk tool on the OpenShift cluster
- 2834781 Register haproxy-ocp tool on masters
- 89476b8 Add unit tests for pbench-fio bench-script
- c46a8e7 Add support to fio to collect the info requested
- 9f96951 Add unit tests for uperf bench-script
- 85173ec Add support to uperf to collect the info requested
- 07a5045 Add unit tests
- 6a9c902 Add support to moongen to collect the info requested
- 3d0ff25 Do not assume that unit tests are sequentially numbered
- 9842b5f Show labels of oc-nodes

* Version 0.43

** Installation                                                    :external:

There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install or update.

After installation or update, you should have version 0.43-1g87c4f83
of the pbench-agent RPM installed.

** agent

*** Known problems and backward incompatibilities

- =pbench-user-benchmark= will now produce a warning about a non-existent
  JSON result file (see below).
- =pbench-fio= issues two warnings after postprocessing the latency log
  files.  This is caused by the last two lines in two of these files
  having the same timestamp. This is probably a fio bug.
- The Python Pandas package goes by different names on RHEL and
  Fedora.  The current code uses "python-pandas" which works for RHEL,
  but not for Fedora.  The workaround for Fedora is to actually change
  the =pbench-fio= script to install "python2-pandas". We have a work
  item to fix this for the next release.
- Two new dependencies have been added to =pbench-agent=: =perl-JSON=
  and =perl-Switch=. These are used to produce JSON files for the
  results of benchmarks (currently, =pbench-uperf=, =pbench-moongen=
  and =pbench-fio= produce such JSON files). =perl-JSON= is available
  from the standard RHEL and Fedora repos, but =perl-Switch= is only
  available from the standard Fedora repos; on RHEL, you will need to
  add the RHEL "optional packages" repo. This can be done by copying

  https://github.com/redhat-performance/perf-dept/blob/master/repo_files/rhel7-latest.repo

  to =/etc/yum.repos.d=.

*** Bug fixes and enhancements

- pbench-fio produces JSON results now, using the same libraries
  that were used in pbench-uperf and pbench-moongen.

- pbench-user-benchmark also produces a rudimentary JSON result
  file (it only includes a duration for the run), but there are
  provisions to allow the user benchmark to produce a JSON file
  which pbench-user-benchmark will upload for indexing.

- Benchmark directory names contain a time stamp, which previously
  contained colons. This caused difficulties with docker, so the
  timestamp format has been changed to contain only periods. Internal
  timestamps (e.g. in the metadata.log) are still in the original format
  using colons; there is no plan to change those.

- Some benchmark scripts now take an additional option: --sysinfo=<val>
  where <val> can be "default", "all", "none", or a comma-separated
  list of words from the following list: kernel_config, block,
  libvirt, sos, block, topology, ara.  The <val> is passed through to
  pbench-collect-sysinfo, to allow the the user to tailor what kind of
  system information will be collected (if any). E.g.

  pbench-fio --sysinfo=none <other args>

  will not collect *any* system information.

  Although this was meant to be applied generally, currently only
  pbench-user-benchmark has been converted. There are outstanding
  PRs for pbench-fio, pbench-uperf and uperf-moongen to be modified
  the same way - they will be available in v0.44. The rest of the
  benchmark scripts will then follow (probably in v0.45, although
  depending on demand, we may convert some of them earlier).

- A "disk" tool has been added: it runs "df" periodically, collects
  the results and post-processes them to render various graphs.

- There will be a number of documentation changes that will be
  rolled out in the next couple of weeks, out-of-band with the
  releases. Notification will be sent out about those changes
  as they happen.

** server

The script that syncs "satellite" pbench servers to a master server
has been sped up to allow more frequent invocation from cron. However,
the rsyncing itself and (particularly) the unpacking of the synced
tarballs on the master server is still a bottleneck. We have a work
item to improve that in v0.44.

The indexing script continues to be enahnced: it now indexes iostat
tool data, and more information has been added to the metadata:
iterations and samples are now indexed. We are planning to deploy test
versions of the indexer in the next month that will index results and
more tool data (to the staging ES instance), then roll it into the
production server in the v0.44 release.  It is likely however that
we'll iterate a number of times on the indexer in the next few
months.

*** Instructions                                                   :external:
TBD.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.43
:END:
There are no updates to the web-server in this release, but there
is a new RPM that should be identical (other than the version number)
to the previous version. For now, we recommend that you do *not* update:
the testing has been fairly superficial and somewhat inconclusive. We
plan to work on this in the next week or two. We'll send out details
when it's ready.

If you do decide to update, the instructions are standard:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.43-1g87c4f83

** Changelog
This is the list of visible (non-merge, non-unit-test-related) commits
since v0.42:

- 87c4f83 Version bump: v0.43
- a0811d9 Fix unit tests.
- caf4a37 Fix fio-postprocess
- 86213bf Fixes to pbench-fio.
- 1c0a117 fio: convert to json for metric data
- 29a365d generate-benchmark-summary: process iterations in numerical order
- 7134e34 Fix unit tests for pbench-rsync-satellite.
- cbb782f Add cleanup script
- 6595a23 Speed up the rsync script.
- bca3c94 Add containerized pbench for openshift
- 1fc8e0c Add unit tests
- eca3b7b Add support to user-benchmark to emit a json file
- c9c21ad Add support to fetch kube config from master
- 597a006 Unit test for index-pbench added
- 7052f9e Handle exceptions more selectively
- 4861e03 Modify index-pbench for pbench-user-benchmark
- b073599 pbench-rsync-satellite: add unit test
- 533f55e pbench-rsync-satellite: bug fixes and unittest prep
- 019031b Send mail only if a counter is nontrivial
- b03b8fb pbench-metadata-log: reduction of ssh invocations
- b0d6b8d Add flexible way to register tools on nodes
- 7fd3b2a Fix df command to ignore openshift volumes, header
- c2f7da9 Change time format in suffix of run directory
- a66c892 Rename variable to avoid collision
- 8207437 Fix syntax of the check
- e389968 Add disk tool to pbench
- 042e3b5 Add mock for pbench-metadata-log unitests
- 3771cbc Update all the benchmarks to call pbench-metadata-log directly
- 6b37e67 Break out of loop in exception handler
- d20464f documentation for pbench-fio and pbench-uperf
- 6fb57e5 Add support to collect-sysinfo to collect ara data
- cc9460b Rename openshift-metrics to prometheus-metrics
- 334f93e Use 'exited' instead of 'failed' on success
- d96c01c Fix playbook to handle non-existant groups in inventory,labeling
- 9645ccb Rework help and usage for user-benchmark
- bdf6f0c Rename the tar files to remove confusion, instead of, compress the tar ball
- 8abd2e8 Use RPM to avoid issues with dashes in awk
- 681a0ef Close using the proper file variable
- d915a3a Fix up dates to put them in standard format
- 4620b28 Add support to pbench-collect-sysinfo to collect only the info requested
- 39935b0 One version file to rule them all
- 9a29587 Contrib VERSION
- f8c76ba Fix the timestamp format
- b4e1b55 Fix WONT-INDEX.xx range to reflect the errors that index-pbench returns
- 80947ed Fix path of index-pbench, PYTHONPATH and config file path.
- 9a5052e Final changes for automating server installation
- b7fd923 Do not try to yum install packages to provide semanage/restorecon
- ac6e5b7 correct timezone to UTC while os.stat'g tb fname
- 3a270ca Index .csv tool data files
- 1df7eff Decompose iteration names into components
- 77783ae Change the date format in agent/base to satisfy ES needs

* Version 0.42

** Installation                                                    :external:
N.B. COPR has deleted the Fedora 23 chroot, so we can no longer
produce Fedora 23 packages; Fedora 23 is no longer supported.

There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install or update.

After installation or update, you should have version 0.42-1gcf7a941
of the pbench-agent RPM installed.

** agent

*** Backward incompatibilities
None known.

*** Bug fixes and enhancements

User-visible changes include:

- HAProxy OCP plugin has been merged
- openshift-metrics tool has been merged
- pbench-clear-tools regained its --remote option (it was lost some time ago).
- pbench-uperf post-processing catches more errors and recovers much better
  than before.

One thing that did not make it is the JSON output for =pbench-fio=:
there were some problems which we didn't have time to address in this
cycle. It will be in v0.43.

** server

Indexing work has been proceeding on a branch. It has not been merged onto the master
branch yet and is not part of this release. The plan is to merge it after the release and
deploy it with the next release.

The server has seen fixes for installing into different environments.

*** Instructions                                                   :external:
TBD.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.42
:END:
The pbench-web-server RPM has been updated with scatterplot support
and a number of fixes.

If you have it installed, you will want to update:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.42-1gcf7a941.

** Changelog
This is the list of visible (non-merge, non-unit-test-related) commits
since v0.41:


- 00d4fe0 Fix command to parse openshift inv
- e9c6634 White space fixes - also fixed some typos
- fc479c4 pbench-metadata-log changes to record iterations
- 1d3508a All pbench benchmark scripts record their iterations
- 78a3b6b Pbench agent base script: do not recalculate $date
- c07a010 Check whether selinuxenabled exists before calling it
- eadc311 Add remote option to pbench-clear-tools
- fab942f Added test fix too
- 0e13532 Fix typo
- 15a8bd1 playbook to register pbench-tools on openshift cluster
- ced507a Fixes distributed-system-analysis/pbench#479
- d24406d Specify the sorting columns explicitly
- 8151b84 Fix invocation of index-pbench
- b38b247 openshift-metrics tool for pbench
- cf950a8 Check ssh status in pbench-rsync-satellite
- 0f545e3 generate-benchmark-summary: skip over missing result.json iterations
- c851d60 pbench-uperf: allow any process-iteration-samples failure to re-try
- ab0cb7b Fix unit tests
- 45a571e Decorate the mail sent by server scripts with environment information
- d120260 Update to pbench-uperf --help
- 29b2929 Fill gaps in server installation
- fee78ab Add scatterplot support to jschart
- 6600716 Correct invalid jschart API calls
- 683c0d1 Fix date format for seconds since epoch
- b58ff7b BenchPostprocess.pm: fix div by zero and other small clean-ups
- eebd592 Added haproxy-ocp unittests.
- ff46508 Set thresholds on graphs with 0 values.
- 702aa8f Collect HAProxy's version and default settings.  Set thresholds on graphs with 0 values.
- c16d833 - Split logs directory to config/logs. ...
- d103e31 Replacing BASH_SOURCE variable.  Assuming plugins will not be 'sourced' by other scripts.
- cda6444 Adding HAProxy OCP plugin.


* Version 0.42

** Installation                                                    :external:
N.B. COPR has deleted the Fedora 23 chroot, so we can no longer
produce Fedora 23 packages; Fedora 23 is no longer supported.

There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install or update.

After installation or update, you should have version 0.42-1gcf7a941
of the pbench-agent RPM installed.

** agent

*** Backward incompatibilities
None known.

*** Bug fixes and enhancements

User-visible changes include:

- HAProxy OCP plugin has been merged
- openshift-metrics tool has been merged
- pbench-clear-tools regained its --remote option (it was lost some time ago).
- pbench-uperf post-processing catches more errors and recovers much better
  than before.

One thing that did not make it is the JSON output for =pbench-fio=:
there were some problems which we didn't have time to address in this
cycle. It will be in v0.43.

** server

Indexing work has been proceeding on a branch. It has not been merged onto the master
branch yet and is not part of this release. The plan is to merge it after the release and
deploy it with the next release.

The server has seen fixes for installing into different environments.

*** Instructions                                                   :external:
TBD.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.42
:END:
The pbench-web-server RPM has been updated with scatterplot support
and a number of fixes.

If you have it installed, you will want to update:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.42-1gcf7a941.

** Changelog
This is the list of visible (non-merge, non-unit-test-related) commits
since v0.41:

- 00d4fe0 Fix command to parse openshift inv
- e9c6634 White space fixes - also fixed some typos
- fc479c4 pbench-metadata-log changes to record iterations
- 1d3508a All pbench benchmark scripts record their iterations
- 78a3b6b Pbench agent base script: do not recalculate $date
- c07a010 Check whether selinuxenabled exists before calling it
- eadc311 Add remote option to pbench-clear-tools
- fab942f Added test fix too
- 0e13532 Fix typo
- 15a8bd1 playbook to register pbench-tools on openshift cluster
- ced507a Fixes distributed-system-analysis/pbench#479
- d24406d Specify the sorting columns explicitly
- 8151b84 Fix invocation of index-pbench
- b38b247 openshift-metrics tool for pbench
- cf950a8 Check ssh status in pbench-rsync-satellite
- 0f545e3 generate-benchmark-summary: skip over missing result.json iterations
- c851d60 pbench-uperf: allow any process-iteration-samples failure to re-try
- ab0cb7b Fix unit tests
- 45a571e Decorate the mail sent by server scripts with environment information
- d120260 Update to pbench-uperf --help
- 29b2929 Fill gaps in server installation
- fee78ab Add scatterplot support to jschart
- 6600716 Correct invalid jschart API calls
- 683c0d1 Fix date format for seconds since epoch
- b58ff7b BenchPostprocess.pm: fix div by zero and other small clean-ups
- eebd592 Added haproxy-ocp unittests.
- ff46508 Set thresholds on graphs with 0 values.
- 702aa8f Collect HAProxy's version and default settings.  Set thresholds on graphs with 0 values.
- c16d833 - Split logs directory to config/logs. ...
- d103e31 Replacing BASH_SOURCE variable.  Assuming plugins will not be 'sourced' by other scripts.
- cda6444 Adding HAProxy OCP plugin.

* Version 0.41

** Installation                                                    :external:
There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install.

After installation or update, you should have version 0.40-1gf281562
of the pbench-agent RPM installed.

** agent

*** Backward incompatibilities
None known.

*** Bug fixes and enhancements

User-visible changes include:

**** New pbench-mpt benchmark
Thanks to Ottavio Piske for this addition which runs msg-perf-tool.

**** =pbench-fio=
Various fixes to the recently added latency histogram functionality.

**** iostat graphs
Improve the graph descriptions by adding units to them. This is
probably just a stopgap first step: there are plans to make various
graph characteristics specified easily and in some cases customizable
by the user.

**** =pbench-moongen=
Add latency data plus various fixes.

**** Fixes to graph rendering
See [[#web-server-0.41][web-server]] below.

** server

- Various fixes to rsyncing from satellite servers.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.41
:END:
The pbench-web-server RPM has been updated with many fixes, cleanups
and optimizations: sort table datasets by value, dataset cursor value
locking, add a "Misc. Controls" panel to the table.

If you have it installed, you probably want to update:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.41-1g97296c4.

** Changelog
This is the list of visible (non-merge, non-unit-test-related) commits
since v0.40:

- f780656 Fix a latency processing bug in moongen-postprocess
- 8a9f445 Unit test gold files changes for PR#434
- bc787eb Fix benchmark postprocessing infloop
- d8ef7ff Add a "Misc. Controls" panel to the jschart table
- eced272 Don't call fiologparser_hist.py twice
- 49fafc2 Fix iostat unit tests.
- aca5ffc Change the iostat keys to more accurately reflect the nature of the metrics
- 4580156 Fix iostat unit tests
- eadcde1 Change the keys of the iostat hash to make them more descriptive
- 9672161 Collect the kernel config file
- f9bc55a use correct units for fio histogram-derived latency graph
- e1a6825 add 95th percentile to fio histogram-derived latency graph
- acfff77 Update jschart by adding dataset cursor value locking
- 5426fab Update jschart to sort the table datasets by value
- f902160 pass job file to fiologparser_hist.py
- 5068ed0 Fix short-form -n option
- be6172f Only display the information about the location of the test results when actually running a test
- 2a80577 The script does not require any options for the install-only mode, therefore prevent checking the test options
- b487f24 Changes the order on which the help options are presented to the user to match the order they are declared
- a505370 Fixes handling of long options, which were missing in the previous versions of the script
- f207c4b Removes the logic to set the default throttle because it is already set earlier
- 02d8ae7 Added support for 'install only' option, which can be used to install mpt dependencies on the test host
- 27547a3 Added support for installing packages from Fedora COPR repositories (WIP)
- 076f496 Minor cleanups by removing unused code on pbench-mpt script
- 1badc9e Added a simple runner script for msg-perf-tool.
- 35ee777 Fix incorrect addressing of 'webserver' variable that would prevent rendering host_info_url setting.
- dc14a7b Downgrade sysstat further to 11.2.0
- 84878ca Downgrade pbench-sysstat req to 11.4.1
- d413085 Allow the user to tell pbench-moongen to accept negative packet loss
- 7bb0c24 Update pbench-moongen to use lua-trafficgen
- 47cca9c Parse new moongen output to find latency data
- 5f898e3 Bump the required sysstat version to 11.5.1
- 6ac5318 Event collection has to be for all namespaces
- 3e03486 Typo
- dbefb1b Crontab entries for satellite handling
- e4d9fe9 Define all relevant variables in pbench-base.sh
- 4b473f7 Improvements to status email
- d23a302 Clean up the status mail
- bbffa61 pbench-rsync-satellite: Fix tarball deletions and send status email

* Version 0.40

** Installation                                                    :external:
There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install.

After installation or update, you should have version 0.40-1gf281562
of the pbench-agent RPM installed.

** agent

*** Backward incompatibilities
None known.

*** Bug fixes and enhancements

User-visible changes include:

**** =pbench-fio=
The pbench-fio script has undergone significant enhancements in order
to take advantage of several facilities implemented in the upstream fio
project. In particular, it gathers and reports latency histograms as
implemented by Karl Cronburg.

*N.B.* The script that processes the logs to get the histograms uses the
Python Pandas library. This script only runs on the controller, so the
library has to be installed there. =pbench-fio= tries to install the library
and it should succeed e.g. on Fedora systems. On RHEL systems however, the
=python-pandas= library is available from EPEL, but not from the standard
installation repos. You will therefore need to install the EPEL repo before
running =pbench-fio= on your controller. Details on EPEL can be found [[https://fedoraproject.org/wiki/EPEL][here]].

The process is as follows: on your RHEL7 controller (and similarly for RHEL6)
#+BEGIN_EXAMPLE
cd /tmp
curl --output ./epel-release-latest-7.noarch.rpm  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install ./epel-release-latest-7.noarch.rpm
#+END_EXAMPLE
After that, the =pbench-fio= script should be able to find and install
the =python-pandas= package.

*N.B.* You need the 2.14-9 (or later) version of the pbench-fio RPM,
which is available from the COPR pbench repo. This RPM is based on current
upstream fio master. The =pbench-fio= script will check for and install
this version, but please bear the dependency in mind if something goes
wrong.

You can now explicitly pass a fio job file to the script, instead of
or in addition to specifying fio options on the command line. We generally
recommend using the command line options for simple usage where that suffices,
but if you need options that =pbench-fio= does not implement, then using
a job file will be necessary.

You can run fio on a set of clients either by using the --clients=... option
to =pbench-fio=, explicitly listing the set of clients; or you can use the
--client-file=... option to pass a file containing the list of clients, one
client per line.

**** =pbench-moongen=
New options.

**** pbench-user-benchmark
The variable specifying the run directory, =benchmark_run_dir=, is now
exported by the main script, making it available to the user-provided
benchmark script (e.g. for squirreling away stuff to package up with the
rest of the data for storage/processing on the server).

This is only one part of a larger [[https://github.com/distributed-system-analysis/pbench/issues/349][issue #349]].

**** Triggers
Trigger functionality has been restored.

**** Hardening of tools-<group> directory handling
In some cases, additional files or subdirectories in the tools-default (or
more generally, tools-<group>) directory have caused problems. We now skip
subdirectories and check files against the available tools list, skipping
any that don't match. A warning is issued in either case suggesting that
the suspect file/subdirectory be removed.

**** Fixes to graph rendering
See [[#web-server-0.40][web-server]] below.

** server

- Add mail notifications to the scripts that backs up results tarballs
  for safekeeping.

- Add verification script to detect bit-rot in tarballs.

- We now run a cron job to fetch tarballs from "satellite" servers and
  store them on our "production" server. The intent is to relieve some
  of the disk space pressure on the satellite, and to take advantage
  of the backup and bit-rot detection facilities that we employ on the
  production server.

- An additional script to age out results on a satellite server is in
  the works but is not running yet.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.40
:END:
The pbench-web-server RPM has been updated with many fixes, cleanups
and optimizations. The major user-visible change is better handling
of outliers - see [[https://github.com/distributed-system-analysis/pbench/issues/317][issue #317]].

If you have it installed, you probably want to update:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.40-1gf281562.

** Changelog
This is the list of visible (non-merge, non-unit-test-related) commits
since v0.39:

- 5409667 Make client file pathname absolute
- 0192eda Check for and install python-pandas
- fa328b4 use a smaller port number increment to allow greater scalability
- 7e98d63 change --cache-drop-script to --pre-iteration-script
- 988c586 Add --dst-macs option to pbench-moongen
- c7420f9 Save client file in the run directory
- 19cf29d Redirect various "No such file or directory" messages to /dev/null
- 1301c1a Fix label complaint in tools-<group> sanity checking code
- de11f82 Pass file from --client-file option directly to fio
- f53293a pbench-list-triggers rewrite.
- cd3dfb5 Grammar and spelling updates to the jschart docs
- fa45c15 Check for spurious files/subdirectories of tools-<group> dir
- e19d81a Fix triggers
- 4a83b02 Update jschart API call in fio-postprocess-viz.py
- ad84dca Update unit tests for new jschart API
- 0cfe6b7 Add View Port Controls to jschart
- 1fd5b11 Use the create_jschart interface
- 5dad7d0 Add documentation to jschart and do minor cleanups
- 60f2a52 Update jschart to include the number of histogram buckets in the table
- abdcec5 Update jschart to show the datapoints on highlighted datasets for histogram and xy charts
- 1cb8864 Delete remote tarballs after checking.
- 480b20a Sync satellite to master.
- 4c1f1e4 Move bad-md5 links to their own state directory.
- 9202d3d Fix some typos in pbench-uperf help strings.
- 7d0f360 Add/fix help string to pbench_fio.
- 65de78b Add verify script for backup tarballs.
- cc8594a Fix a subsitution bug in BenchPostprocess::get_uid
- b8995ed Add new MoonGen queue control options
- 3a13b5a Process only the last moongen validation phase
- d21fd21 Add mail notification for pbench-backup-tarballs
- 0465506 Fixes to fully handle epoch time: - Parse job file from fio-postprocess-viz.py to detect when log_unix_epoch is present (using 'timeseries' instead of 'xy' in jschart) - jschart expects ms not s (no more divide by 1000 on time values) - Pass job file parameter whenever we call fiologparser_hist.py and fio-postproces-viz.py - Update to make-fio-jobfile.py to handle config options without values (e.g. 'stonewall' in fio)
- b0fff69 Add pprof heap support
- 930ee68 Run fiologparser_hist.py during postprocessing, and generate jschart HTML docs showing the histogram data for each individual sample as well as (merged) across all samples for a particular iteration.
- 1c52ee2 Make the run directory available to the called user script.
- debc148 Templating prototype for `pbench-fio`, using config files to specify fio parameters. The order of precedence used is as follows: (from high to low)
- 5958d94 Add --client-file option to specify a list of clients
- 3fd2741 Remove redundant $bench_opts
- bbe6b9b Ensure --samples is documented in --help
- f9d939e Ensure $client is assigned before it is referenced
- a5ed3eb use correct benchmark name
- da5928e Respect GOROOT env var if set
- 5969500 Fix exit status of pbench-{move/copy}-results.

* Version 0.39

** Installation                                                    :external:
There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install.

After installation or update, you should have version 0.39-3g4f9ab11
of the pbench-agent RPM installed.

** agent
*** Backward incompatibilities
**** pbench-agent config file renamed
All configuration files now have a suffix of ".cfg", rather than
".conf".  In particular, the default pbench-agent config file is now
~/opt/pbench-agent/config/pbench-agent.cfg~.  You might have to rename
your existing config file:
#+BEGIN_EXAMPLE
cd /opt/pbench-agent/config
mv pbench-agent.conf pbench-agent.cfg
#+END_EXAMPLE
If you have problems (e.g. =pbench-register-tool-set= only registers the ~perf~
tool, rather than a complete set; =pbench-move-results= fails because it cannot
find a server), check with:
#+BEGIN_EXAMPLE
cat $CONFIG
#+END_EXAMPLE
If that fails, then pbench cannot find the config file, most probably because
of the renaming described above.
**** pbench-netperf script has bit-rotted
The pbench-netperf script seems to have bit-rotted. We are trying to
decide whether to fix it or abandon it. If you have an opinion, please
comment at https://github.com/distributed-system-analysis/pbench/issues/291.

*** New features
Please submit suggestions/issues to the [[https://github.com/distributed-system-analysis/pbench/issues][issue tracker]].

**** JSON files for pbench-uperf
The postprocessing now produces JSON files that we are planning to use
in order to index benchmark results and tool output into ES. The
backend work necessary to index these results will be done between
v0.39 and v0.40 and might necessitate changes to the JSON output. So
pbench-uperf is treated as a guinea pig and once the output format
solidifies, the rest of the benchmarks are going to be converted as
well, probably starting with pbench-fio.

A large part of the work for pbench-uperf has been to refactor the
pbench-uperf script, so that the resulting pieces can be
reused. Andrew hopes to have 90% of each benchmark script code in
reusable packages, which will also simplify adding new scripts in the
future.

**** The pbench docs on github have been revamped
The docs can now be processed in two ways: to produce "internal"
documents, including the more automated installation that is possible
internally, as well as "external" documents that are more generic and
depend only on externally available resources.

The docs on github have been replaced by the "external" documents:
there are still some ~example.com~ fake URLs (clearly marked, we hope)
but almost all URLs now point to their correct referent and the instructions
should be enough to get pbench-agent/pbench-server/pbench-web-server installed
in an arbitrary environment, but with some manual work required (again, clearly
described, we hope, even if it is somewhat laborious).

*** Bug fixes

**** Better error handling by utility scripts
In particular, errors in ssh invocations in pipelines are caught and returned
properly. More work is planned in this area for upcoming releases, in particular
hardening the benchmark scripts so that they deal better with errors and signals.

**** Safer killing of tools
A safer kill has been implemented for all the tools that are linked to
=kvm-spinlock=.  Assuming no problems surface, the sar-based tools
will get the same treatment in upcoming releases.

**** Screen session names were too long
The screen command fails when the name of the screen session (-S) is
very long. This happens when the iteration full name is quite long. A
fix for this uses only the iteration number, reducing the screen
name to a safe length.
**** Fixes to graph rendering
See [[#web-server-0.39][web-server]] below.

** server
Server installation was simplified in v0.38: there is an RPM on COPR that can be used
for installation, but as for the pbench-agent, it is not completely self-contained: one
needs to install various configuration files and generate a directory structure for apache,
a directory structure for results and a crontab that invokes the various scripts to process
incoming results and make them available for viewing on the web.

This release adds scripts to do these tasks somewhat more conveniently. It is possible to
use these scripts from an RPM that installs the config files and then invokes the scripts to
finish the installation. But it is also possible to do these steps manually. See the
[[file:~/src/internal/pbench/doc/server/installation.org][server installation guide]] for details.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.39
:END:
The pbench-web-server RPM has been updated with many fixes, cleanups
and optimizations.  Changes that are user-visible are:

- Update jschart to better handle errors while loading datasets
- Update jschart to support alternative csv file formatting
- Fix a jschart bug where the wrong clip-path is referenced
- Update jschart to add percentiles to the values displayed in the
  table when the mouse is moving across a histogram chart

If you have it installed, you probably want to update:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.3-19gaf1ffe4.

** Changelog
- 9c2554f Bump versions for various benchmarks.
- a02ad33 Bump VERSION.
- 48b8c27 Fix condition for warning of already running tools.
- f4f5618 Add unit tests.
- cf59a06 Check status of backgrounded commands in pbench-postprocess-tools.
- fe15a81 Catch pipeline failures and return proper error status.
- 75ca51c Use pidof -x to get list of pids.
- 7bbb4dd Revert the change to perf.
- 11a0ad9 Add unit tests for safe_kill.
- fa80b08 Safer kill: check for strange situations and deal with them.
- 862e68b Change the name of the config file in profile.
- 9e0ecef Fix pbench-agent-config-activate and add unit test.
- 19039eb Allow partial execution of unittests.
- 57b56e7 Fix links to point to DSA github.io area.
- d720f61 updated pprof to point to correct package name for "go" it is golang, not go - added tool_bin to point to /usr/bin/go
- ee321d6 Add missing '$'
- d38ba9b Reduce screen session name to avoid screen error
- 66c6996 Update jschart's d3-queue support from version 2 to version 3
- bc34df8 Update jschart to support alternative csv file formatting
- 343f715 Fix a jschart bug where the wrong clip-path is referenced
- 333978c Update jschart to add percentiles to the values displayed in the table when the mouse is moving across a histogram chart
- 8608c57 Update jschart to better handle errors while loading datasets
- cae9788 Update jschart by eliminating the use of map
- 2423475 Bug fix for jschart to pass a proper reference to the SVG to saveSvgAsPng
- 826e5d7 Update jschart by eliminating as many global variables as possible to avoid out of scope references
- 521cb95 Update jschart to minimize global variable references to the charts object
- 74b30a8 Update jschart with cleanups and optimizations
- 932679a Benchmark and iteration summary/processing scripts, JSON files and MoonGen benchmark support
- 775f208 Remove duplicate data collected by sosreports
- a395811 Links to revised documentation.
- e6605d6 Add memory usage pidstat graphs
- 124c787 Server installation link added.
- feb8aed bgtasks --> pbench-server
- f51df98 Links to revised docs.
- d21eefa Server version bump.
- 66382bb Add server activation unit test.
- 455c7f8 Fix command path.
- df7aaab Allow different set-ups during server activation.
- b63bdf5 Fix quoting of patterns for pidstat.

* Version 0.38

** Installation                                                    :external:
There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install.

After installation or update, you should have version 0.38-1g0db11ba
of the pbench-agent RPM installed.

** agent
*** Backward incompatibilities
In the v0.36 timeframe, all pbench scripts and benchmarks that are
normally accessible were renamed: those that did not have a prefix at
all were renamed with a "pbench-" prefix; the benchmarks had a
"pbench_" prefix and were renamed for consistency with a "pbench-"
prefix as well.

In v0.37, there were compatibility links to the old names in util-scripts.

In v0.38, these links have been deleted: you will have to make sure
that you use (and all your scripts use) the names with the "pbench-"
prefix.

*** New features
Please submit suggestions/issues to the [[https://github.com/distributed-system-analysis/pbench/issues][issue tracker]].

**** New graphs

The major change in this release is the replacement of the original
nvd3 graphs with graphs produced by a library written by Karl Rister.
The advantage of this library is that it is much less demanding on
the browser than the original graph library.

Note that it uses the same CSV files that the original graphs used,
which it downloads from the server[fn:1]: big data sets are still
going to incur long time penalties for the transfer. The difference is
that once the download is complete, your browser will stand a much
better chance of staying alive and able to display the graphs.

[fn:1] Unless you install locally - see [[http://pbench.example.com/server/pbench-web-server.html][PBench web server]] for instructions.

*** Bug fixes

**** Fixed the RPM names for tools and benchmarks to include the pbench- prefix
PBench will now be able to find and install the correct RPMs (with the
current exception of pbench-iperf as noted above).

**** Fixed the URL for the COPR repo
The documentation on GitHub was pointing to a non-existent place for
the COPR pbench-agent RPM: it used a sanitized =example.com=
address. This was fixed, but note that the documentation still
contains dead links and will undergo a significant overhaul for
the next release.

**** The pbench-kiil-tools symlink in the repo was wrong.
That was fixed, but the bug did not and does not have any effect on a
local installation: those symlinks are created on the fly by an RPM
%post action.

**** The sar script was modified to handle user-defined options.
Note however that if you use non-standard options, the postprocessing
step for the sar tool (and its relatives) will be skipped, since
pbench does not know how to handle the modified output.


** server                                                          :external:
The server has now been organized in the same way as the agent: there
is an external RPM available from COPR that includes all the scripts,
and some configuration scripts that can be used to install the config
file and perform the rest of the server configuration. See the [[file:../server/installation.org][server
installation guide]].

** web-server

There is an RPM available on COPR that allows local viewing of graphs,
both in the v0.2 format (Andrew's graphs using nvd3) or in the v0.3
format (Karl's graphs using d3). This now includes Karl's latest fixes.
If you have installed an older version, please upgrade. The current version
on COPR is 0.3-10.

** Fedora 24 RPMs on COPR

Fedora 24 has been added to the build list and Fedora 21 has been
deleted from it, for all the RPMS (benchmarks, tools,
pbench-agent, pbench-server, pbench-web-server, configtools).

One benchmark RPM (=pbench-iperf=) is currently failing to build. This
will be fixed shortly.

** Changelog
- 4a65484 Version bump.
- 0d5a976 Delete compatibility wrapper.
- 2dff665 Wrong link for pbench-kill-tools.
- 58dbb63 Update jschart and fix a small bug by cleaning up the y axis label updating code
- a9ac750 Fix a bug in the jschart tooltip implementation when the tooltip belongs to an Y axis label
- 8ca3d37 Long overdue cleanup of the jschart style and class code
- 99fc942 Update the jschart legend rectangle outlining code to work with Firefox and vector zooming
- ef211e8 Update jschart live_update to a timeseries data model which uses milliseconds since the epoch timestamps
- b4372f6 Update jschart with a new filtering capability based on the dataset name and resort the table (if sorting is enabled) when datasets are hidden or unhidden
- 281d89c Update the jschart show/hide all events to use static functions with locally scoped variables
- 9453829 Update jschart threshold application events to use static functions with locally scoped variables
- 76590ed Update the the jschart dataset mouseover, mouseout, and click events to use static functions with locally scoped variables
- 844b87b Update the jschart viewport event handlers to use static functions with locally scoped variables instead of closures
- 3bef541 Update jschart to eliminate some calls to map that are made often during some runtime behaviors
- 6dbc809 Update jschart by replacing many data accesor closures with static functions
- 82a0151 Update jschart to display the datasets value in the table that most closely aligns with the cursor's position in the viewport
- 3a8cd33 Remove some dead code from jschart
- 94c0808 Update the jschart table creations to use D3 principles to improve maintainability and reduce code bloat
- c332ef9 Update jschart to improve maintainability and performance
- 5d83c24 Update jschart to be able to apply a dynamic threshold based on a a dataset's maximum y value or y mean
- 325f17e Update the jschart live update controls to fix some bugs introduced with the recent code churn
- 25bf0b1 Update jschart to automatically sort the datasets in descending order based on their mean by default
- 5ea4df3 Update jschart to honor the threshold and use it to determine if datasets should be automatically hidden
- b276f78 Move some jschart hard coded values into global variables for easier maintanance and use moving forward
- 3a45dfa Update jschart to be more dynamic when hiding and unhiding datasets
- 44d5238 Allow hidden datasets in jschart to be unhidden by clicking their table row
- 9b000bf Add jschart support for log scale on the x and y axis
- 3534f88 Update the jschart axes references to conform to other chart object references
- 3bce44d Update the jschart axes without doing DOM searches
- a1af8da Refactor the code to use a global array of chart objects with references to all chart elements and data that may be accessed at runtime
- b1e93ea Squash some tooltip bugs
- 69813a4 Add the ability to hide all or individual datasets and the requisite ability to unhide them
- 09f33a5 Refactor the dataset highlighting code to track state and improve performance
- 5f0e909 Add a link from a chart_ref to it's datasets and links from the datasets to their DOM objects
- bf5732f Update the legend boxes to always have a constant colored outline
- e15db96 Update the description and dependency information for jschart
- bbc21f0 Update the wording that refers to the EPL LICENSE.TXT file locations
- dcbf39b Update the verbage in the demo web server to better reflect it's usage
- 388d319 Add a simple web server from LPCPU for use in demoing/testing jschart
- 43ed280 Add a jschart demo for testing purposes
- db0ece1 Add support for a new data model type called histogram
- c99c7d3 More jschart whitespace formatting cleanups
- c8cfe1e Fix a bug in the jschart "Apply X-Axis Zoom to All" feature caused by the new support for timeseries charts
- a2f1056 Fix some bugs in the zoom_it function in jschart when the data model is timeseries:
- e471473 Remove dead code from the handle_brush_actions function in jschart
- 87c7647 Update the mouse coordinate display to support when the chart is timeseries
- 583ef9e Fixup timezone and time formatting support, defaulting to UTC
- 9f0a3a7 Update jschart to use a dynamic x-axis label showing the (zoomed) time range when the chart is timeseries
- 3534125 Update GenData to use jschart
- bb36819 Update jschart to be compatible with GenData chart type specifications
- 3b3889f Update the jschart highlight functions to have more descriptive names
- 1f354a7 Update D3 Queue initialization to match d3-queue code available via npm
- 28d51b9 Add support for saveSvgAsPng to jschart
- 3029052 Add support for specifying whether a jschart is a XY plot or timeseries
- 247216b Remove the jschart assertion that the x-axis domain should have a minimum=0 unless otherwise specified
- 72a42e9 Add support for loading CSV data files into jschart
- 785b27c Update jschart.js to dynamically build the summary table at runtime
- c8b781a Initial commit of jschart files pulled from LPCPU
- 7224a5a Clean up the list file.
- ef3f12b Fix the COPR repo URL.
- 6a1e74f Store cron job script logs in the local file system.
- fc9d61d modified oc scrit -> fixed typo -> if decided to start too, instructed to install 'expect' package - necessary for unbuffer
- 02eb062 Fix the calls to check_installed_rpm in all the benchmarks.
- 6c48dbe Script rename: metadata-log --> pbench-metadata-log
- 2b8b991 Modify the sar script (and its relatives) to handle user-defined options.
