# Created 2016-09-22 Thu 16:24
#+OPTIONS: html-link-use-abs-url:nil html-postamble:t
#+OPTIONS: html-preamble:t html-scripts:t html-style:t
#+OPTIONS: html5-fancy:nil tex:t
#+OPTIONS: ^:{} H:2
#+TITLE: PBench release notes
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+KEYWORDS: pbench
#+HTML_LINK_HOME: 
#+HTML_LINK_UP: 
#+HTML_MATHJAX: 
#+HTML_HEAD_EXTRA: 
#+SUBTITLE: 
#+INFOJS_OPT: 
#+LATEX_HEADER: 

* Version 0.40

** Installation                                                    :external:
There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install.

After installation or update, you should have version 0.40-1gf281562
of the pbench-agent RPM installed.

** agent

*** Backward incompatibilities
None known.

*** Bug fixes and enhancements

User-visible changes include:

**** =pbench-fio=
The pbench-fio script has undergone significant enhancements in order
to take advantage of several facilities implemented in the upstream fio
project. In particular, it gathers and reports latency histograms as
implemented by Karl Cronburg.

*N.B.* The script that processes the logs to get the histograms uses the
Python Pandas library. This script only runs on the controller, so the
library has to be installed there. =pbench-fio= tries to install the library
and it should succeed e.g. on Fedora systems. On RHEL systems however, the
=python-pandas= library is available from EPEL, but not from the standard
installation repos. You will therefore need to install the EPEL repo before
running =pbench-fio= on your controller. Details on EPEL can be found [[https://fedoraproject.org/wiki/EPEL][here]].

The process is as follows: on your RHEL7 controller (and similarly for RHEL6)
#+BEGIN_EXAMPLE
cd /tmp
curl --output ./epel-release-latest-7.noarch.rpm  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install ./epel-release-latest-7.noarch.rpm
#+END_EXAMPLE
After that, the =pbench-fio= script should be able to find and install
the =python-pandas= package.

*N.B.* You need the 2.14-9 (or later) version of the pbench-fio RPM,
which is available from the COPR pbench repo. This RPM is based on current
upstream fio master. The =pbench-fio= script will check for and install
this version, but please bear the dependency in mind if something goes
wrong.

You can now explicitly pass a fio job file to the script, instead of
or in addition to specifying fio options on the command line. We generally
recommend using the command line options for simple usage where that suffices,
but if you need options that =pbench-fio= does not implement, then using
a job file will be necessary.

You can run fio on a set of clients either by using the --clients=... option
to =pbench-fio=, explicitly listing the set of clients; or you can use the
--client-file=... option to pass a file containing the list of clients, one
client per line.

**** =pbench-moongen=
New options.

**** pbench-user-benchmark
The variable specifying the run directory, =benchmark_run_dir=, is now
exported by the main script, making it available to the user-provided
benchmark script (e.g. for squirreling away stuff to package up with the
rest of the data for storage/processing on the server).

This is only one part of a larger [[https://github.com/distributed-system-analysis/pbench/issues/349][issue #349]].

**** Triggers
Trigger functionality has been restored.

**** Hardening of tools-<group> directory handling
In some cases, additional files or subdirectories in the tools-default (or
more generally, tools-<group>) directory have caused problems. We now skip
subdirectories and check files against the available tools list, skipping
any that don't match. A warning is issued in either case suggesting that
the suspect file/subdirectory be removed.

**** Fixes to graph rendering
See [[#web-server-0.40][web-server]] below.

** server

- Add mail notifications to the scripts that backs up results tarballs
  for safekeeping.

- Add verification script to detect bit-rot in tarballs.

- We now run a cron job to fetch tarballs from "satellite" servers and
  store them on our "production" server. The intent is to relieve some
  of the disk space pressure on the satellite, and to take advantage
  of the backup and bit-rot detection facilities that we employ on the
  production server.

- An additional script to age out results on a satellite server is in
  the works but is not running yet.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.40
:END:
The pbench-web-server RPM has been updated with many fixes, cleanups
and optimizations. The major user-visible change is better handling
of outliers - see [[https://github.com/distributed-system-analysis/pbench/issues/317][issue #317]].

If you have it installed, you probably want to update:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.40-1gf281562.

** Changelog
This is the list of visible (non-merge, non-unit-test-related) commits
since v0.39:

- 5409667 Make client file pathname absolute
- 0192eda Check for and install python-pandas
- fa328b4 use a smaller port number increment to allow greater scalability
- 7e98d63 change --cache-drop-script to --pre-iteration-script
- 988c586 Add --dst-macs option to pbench-moongen
- c7420f9 Save client file in the run directory
- 19cf29d Redirect various "No such file or directory" messages to /dev/null
- 1301c1a Fix label complaint in tools-<group> sanity checking code
- de11f82 Pass file from --client-file option directly to fio
- f53293a pbench-list-triggers rewrite.
- cd3dfb5 Grammar and spelling updates to the jschart docs
- fa45c15 Check for spurious files/subdirectories of tools-<group> dir
- e19d81a Fix triggers
- 4a83b02 Update jschart API call in fio-postprocess-viz.py
- ad84dca Update unit tests for new jschart API
- 0cfe6b7 Add View Port Controls to jschart
- 1fd5b11 Use the create_jschart interface
- 5dad7d0 Add documentation to jschart and do minor cleanups
- 60f2a52 Update jschart to include the number of histogram buckets in the table
- abdcec5 Update jschart to show the datapoints on highlighted datasets for histogram and xy charts
- 1cb8864 Delete remote tarballs after checking.
- 480b20a Sync satellite to master.
- 4c1f1e4 Move bad-md5 links to their own state directory.
- 9202d3d Fix some typos in pbench-uperf help strings.
- 7d0f360 Add/fix help string to pbench_fio.
- 65de78b Add verify script for backup tarballs.
- cc8594a Fix a subsitution bug in BenchPostprocess::get_uid
- b8995ed Add new MoonGen queue control options
- 3a13b5a Process only the last moongen validation phase
- d21fd21 Add mail notification for pbench-backup-tarballs
- 0465506 Fixes to fully handle epoch time: - Parse job file from fio-postprocess-viz.py to detect when log_unix_epoch is present (using 'timeseries' instead of 'xy' in jschart) - jschart expects ms not s (no more divide by 1000 on time values) - Pass job file parameter whenever we call fiologparser_hist.py and fio-postproces-viz.py - Update to make-fio-jobfile.py to handle config options without values (e.g. 'stonewall' in fio)
- b0fff69 Add pprof heap support
- 930ee68 Run fiologparser_hist.py during postprocessing, and generate jschart HTML docs showing the histogram data for each individual sample as well as (merged) across all samples for a particular iteration.
- 1c52ee2 Make the run directory available to the called user script.
- debc148 Templating prototype for `pbench-fio`, using config files to specify fio parameters. The order of precedence used is as follows: (from high to low)
- 5958d94 Add --client-file option to specify a list of clients
- 3fd2741 Remove redundant $bench_opts
- bbe6b9b Ensure --samples is documented in --help
- f9d939e Ensure $client is assigned before it is referenced
- a5ed3eb use correct benchmark name
- da5928e Respect GOROOT env var if set
- 5969500 Fix exit status of pbench-{move/copy}-results.

* Version 0.39

** Installation                                                    :external:
There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install.

After installation or update, you should have version 0.39-3g4f9ab11
of the pbench-agent RPM installed.

** agent
*** Backward incompatibilities
**** pbench-agent config file renamed
All configuration files now have a suffix of ".cfg", rather than
".conf".  In particular, the default pbench-agent config file is now
~/opt/pbench-agent/config/pbench-agent.cfg~.  You might have to rename
your existing config file:
#+BEGIN_EXAMPLE
cd /opt/pbench-agent/config
mv pbench-agent.conf pbench-agent.cfg
#+END_EXAMPLE
If you have problems (e.g. =pbench-register-tool-set= only registers the ~perf~
tool, rather than a complete set; =pbench-move-results= fails because it cannot
find a server), check with:
#+BEGIN_EXAMPLE
cat $CONFIG
#+END_EXAMPLE
If that fails, then pbench cannot find the config file, most probably because
of the renaming described above.
**** pbench-netperf script has bit-rotted
The pbench-netperf script seems to have bit-rotted. We are trying to
decide whether to fix it or abandon it. If you have an opinion, please
comment at [[https://github.com/distributed-system-analysis/pbench/issues/291]].

*** New features
Please submit suggestions/issues to the [[https://github.com/distributed-system-analysis/pbench/issues][issue tracker]].

**** JSON files for pbench-uperf
The postprocessing now produces JSON files that we are planning to use
in order to index benchmark results and tool output into ES. The
backend work necessary to index these results will be done between
v0.39 and v0.40 and might necessitate changes to the JSON output. So
pbench-uperf is treated as a guinea pig and once the output format
solidifies, the rest of the benchmarks are going to be converted as
well, probably starting with pbench-fio.

A large part of the work for pbench-uperf has been to refactor the
pbench-uperf script, so that the resulting pieces can be
reused. Andrew hopes to have 90% of each benchmark script code in
reusable packages, which will also simplify adding new scripts in the
future.

**** The pbench docs on github have been revamped
The docs can now be processed in two ways: to produce "internal"
documents, including the more automated installation that is possible
internally, as well as "external" documents that are more generic and
depend only on externally available resources.

The docs on github have been replaced by the "external" documents:
there are still some ~example.com~ fake URLs (clearly marked, we hope)
but almost all URLs now point to their correct referent and the instructions
should be enough to get pbench-agent/pbench-server/pbench-web-server installed
in an arbitrary environment, but with some manual work required (again, clearly
described, we hope, even if it is somewhat laborious).

*** Bug fixes

**** Better error handling by utility scripts
In particular, errors in ssh invocations in pipelines are caught and returned
properly. More work is planned in this area for upcoming releases, in particular
hardening the benchmark scripts so that they deal better with errors and signals.

**** Safer killing of tools
A safer kill has been implemented for all the tools that are linked to
=kvm-spinlock=.  Assuming no problems surface, the sar-based tools
will get the same treatment in upcoming releases.

**** Screen session names were too long
The screen command fails when the name of the screen session (-S) is
very long. This happens when the iteration full name is quite long. A
fix for this uses only the iteration number, reducing the screen
name to a safe length.
**** Fixes to graph rendering
See [[#web-server-0.39][web-server]] below.

** server
Server installation was simplified in v0.38: there is an RPM on COPR that can be used
for installation, but as for the pbench-agent, it is not completely self-contained: one
needs to install various configuration files and generate a directory structure for apache,
a directory structure for results and a crontab that invokes the various scripts to process
incoming results and make them available for viewing on the web.

This release adds scripts to do these tasks somewhat more conveniently. It is possible to
use these scripts from an RPM that installs the config files and then invokes the scripts to
finish the installation. But it is also possible to do these steps manually. See the
[[file:~/src/internal/pbench/doc/server/installation.org][server installation guide]] for details.

** web-server
:PROPERTIES:
:CUSTOM_ID: web-server-0.39
:END:
The pbench-web-server RPM has been updated with many fixes, cleanups
and optimizations.  Changes that are user-visible are:

- Update jschart to better handle errors while loading datasets
- Update jschart to support alternative csv file formatting
- Fix a jschart bug where the wrong clip-path is referenced
- Update jschart to add percentiles to the values displayed in the
  table when the mouse is moving across a histogram chart

If you have it installed, you probably want to update:
#+BEGIN_EXAMPLE
dnf clean expire-cache
dnf update pbench-web-server
#+END_EXAMPLE
(or the yum equivalents.)  The current version available from COPR
is 0.3-19gaf1ffe4.

** Changelog
- 9c2554f Bump versions for various benchmarks.
- a02ad33 Bump VERSION.
- 48b8c27 Fix condition for warning of already running tools.
- f4f5618 Add unit tests.
- cf59a06 Check status of backgrounded commands in pbench-postprocess-tools.
- fe15a81 Catch pipeline failures and return proper error status.
- 75ca51c Use pidof -x to get list of pids.
- 7bbb4dd Revert the change to perf.
- 11a0ad9 Add unit tests for safe_kill.
- fa80b08 Safer kill: check for strange situations and deal with them.
- 862e68b Change the name of the config file in profile.
- 9e0ecef Fix pbench-agent-config-activate and add unit test.
- 19039eb Allow partial execution of unittests.
- 57b56e7 Fix links to point to DSA github.io area.
- d720f61 updated pprof to point to correct package name for "go" it is golang, not go - added tool_bin to point to /usr/bin/go
- ee321d6 Add missing '$'
- d38ba9b Reduce screen session name to avoid screen error
- 66c6996 Update jschart's d3-queue support from version 2 to version 3
- bc34df8 Update jschart to support alternative csv file formatting
- 343f715 Fix a jschart bug where the wrong clip-path is referenced
- 333978c Update jschart to add percentiles to the values displayed in the table when the mouse is moving across a histogram chart
- 8608c57 Update jschart to better handle errors while loading datasets
- cae9788 Update jschart by eliminating the use of map
- 2423475 Bug fix for jschart to pass a proper reference to the SVG to saveSvgAsPng
- 826e5d7 Update jschart by eliminating as many global variables as possible to avoid out of scope references
- 521cb95 Update jschart to minimize global variable references to the charts object
- 74b30a8 Update jschart with cleanups and optimizations
- 932679a Benchmark and iteration summary/processing scripts, JSON files and MoonGen benchmark support
- 775f208 Remove duplicate data collected by sosreports
- a395811 Links to revised documentation.
- e6605d6 Add memory usage pidstat graphs
- 124c787 Server installation link added.
- feb8aed bgtasks --> pbench-server
- f51df98 Links to revised docs.
- d21eefa Server version bump.
- 66382bb Add server activation unit test.
- 455c7f8 Fix command path.
- df7aaab Allow different set-ups during server activation.
- b63bdf5 Fix quoting of patterns for pidstat.

* Version 0.38

** Installation                                                    :external:
There are no installation changes in this release: see the
[[file:../agent/installation.org][Installation Instructions]] for how to install.

After installation or update, you should have version 0.38-1g0db11ba
of the pbench-agent RPM installed.

** agent
*** Backward incompatibilities
In the v0.36 timeframe, all pbench scripts and benchmarks that are
normally accessible were renamed: those that did not have a prefix at
all were renamed with a "pbench-" prefix; the benchmarks had a
"pbench_" prefix and were renamed for consistency with a "pbench-"
prefix as well.

In v0.37, there were compatibility links to the old names in util-scripts.

In v0.38, these links have been deleted: you will have to make sure
that you use (and all your scripts use) the names with the "pbench-"
prefix.

*** New features
Please submit suggestions/issues to the [[https://github.com/distributed-system-analysis/pbench/issues][issue tracker]].

**** New graphs

The major change in this release is the replacement of the original
nvd3 graphs with graphs produced by a library written by Karl Rister.
The advantage of this library is that it is much less demanding on
the browser than the original graph library.

Note that it uses the same CSV files that the original graphs used,
which it downloads from the server[fn:1]: big data sets are still
going to incur long time penalties for the transfer. The difference is
that once the download is complete, your browser will stand a much
better chance of staying alive and able to display the graphs.

[fn:1] Unless you install locally - see [[http://pbench.example.com/server/pbench-web-server.html][PBench web server]] for instructions.

*** Bug fixes

**** Fixed the RPM names for tools and benchmarks to include the pbench- prefix
PBench will now be able to find and install the correct RPMs (with the
current exception of pbench-iperf as noted above).

**** Fixed the URL for the COPR repo
The documentation on GitHub was pointing to a non-existent place for
the COPR pbench-agent RPM: it used a sanitized =example.com=
address. This was fixed, but note that the documentation still
contains dead links and will undergo a significant overhaul for
the next release.

**** The pbench-kiil-tools symlink in the repo was wrong.
That was fixed, but the bug did not and does not have any effect on a
local installation: those symlinks are created on the fly by an RPM
%post action.

**** The sar script was modified to handle user-defined options.
Note however that if you use non-standard options, the postprocessing
step for the sar tool (and its relatives) will be skipped, since
pbench does not know how to handle the modified output.


** server                                                          :external:
The server has now been organized in the same way as the agent: there
is an external RPM available from COPR that includes all the scripts,
and some configuration scripts that can be used to install the config
file and perform the rest of the server configuration. See the [[file:../server/installation.org][server
installation guide]].

** web-server

There is an RPM available on COPR that allows local viewing of graphs,
both in the v0.2 format (Andrew's graphs using nvd3) or in the v0.3
format (Karl's graphs using d3). This now includes Karl's latest fixes.
If you have installed an older version, please upgrade. The current version
on COPR is 0.3-10.

** Fedora 24 RPMs on COPR

Fedora 24 has been added to the build list and Fedora 21 has been
deleted from it, for all the RPMS (benchmarks, tools,
pbench-agent, pbench-server, pbench-web-server, configtools).

One benchmark RPM (=pbench-iperf=) is currently failing to build. This
will be fixed shortly.

** Changelog
- 4a65484 Version bump.
- 0d5a976 Delete compatibility wrapper.
- 2dff665 Wrong link for pbench-kill-tools.
- 58dbb63 Update jschart and fix a small bug by cleaning up the y axis label updating code
- a9ac750 Fix a bug in the jschart tooltip implementation when the tooltip belongs to an Y axis label
- 8ca3d37 Long overdue cleanup of the jschart style and class code
- 99fc942 Update the jschart legend rectangle outlining code to work with Firefox and vector zooming
- ef211e8 Update jschart live_update to a timeseries data model which uses milliseconds since the epoch timestamps
- b4372f6 Update jschart with a new filtering capability based on the dataset name and resort the table (if sorting is enabled) when datasets are hidden or unhidden
- 281d89c Update the jschart show/hide all events to use static functions with locally scoped variables
- 9453829 Update jschart threshold application events to use static functions with locally scoped variables
- 76590ed Update the the jschart dataset mouseover, mouseout, and click events to use static functions with locally scoped variables
- 844b87b Update the jschart viewport event handlers to use static functions with locally scoped variables instead of closures
- 3bef541 Update jschart to eliminate some calls to map that are made often during some runtime behaviors
- 6dbc809 Update jschart by replacing many data accesor closures with static functions
- 82a0151 Update jschart to display the datasets value in the table that most closely aligns with the cursor's position in the viewport
- 3a8cd33 Remove some dead code from jschart
- 94c0808 Update the jschart table creations to use D3 principles to improve maintainability and reduce code bloat
- c332ef9 Update jschart to improve maintainability and performance
- 5d83c24 Update jschart to be able to apply a dynamic threshold based on a a dataset's maximum y value or y mean
- 325f17e Update the jschart live update controls to fix some bugs introduced with the recent code churn
- 25bf0b1 Update jschart to automatically sort the datasets in descending order based on their mean by default
- 5ea4df3 Update jschart to honor the threshold and use it to determine if datasets should be automatically hidden
- b276f78 Move some jschart hard coded values into global variables for easier maintanance and use moving forward
- 3a45dfa Update jschart to be more dynamic when hiding and unhiding datasets
- 44d5238 Allow hidden datasets in jschart to be unhidden by clicking their table row
- 9b000bf Add jschart support for log scale on the x and y axis
- 3534f88 Update the jschart axes references to conform to other chart object references
- 3bce44d Update the jschart axes without doing DOM searches
- a1af8da Refactor the code to use a global array of chart objects with references to all chart elements and data that may be accessed at runtime
- b1e93ea Squash some tooltip bugs
- 69813a4 Add the ability to hide all or individual datasets and the requisite ability to unhide them
- 09f33a5 Refactor the dataset highlighting code to track state and improve performance
- 5f0e909 Add a link from a chart_ref to it's datasets and links from the datasets to their DOM objects
- bf5732f Update the legend boxes to always have a constant colored outline
- e15db96 Update the description and dependency information for jschart
- bbc21f0 Update the wording that refers to the EPL LICENSE.TXT file locations
- dcbf39b Update the verbage in the demo web server to better reflect it's usage
- 388d319 Add a simple web server from LPCPU for use in demoing/testing jschart
- 43ed280 Add a jschart demo for testing purposes
- db0ece1 Add support for a new data model type called histogram
- c99c7d3 More jschart whitespace formatting cleanups
- c8cfe1e Fix a bug in the jschart "Apply X-Axis Zoom to All" feature caused by the new support for timeseries charts
- a2f1056 Fix some bugs in the zoom_it function in jschart when the data model is timeseries:
- e471473 Remove dead code from the handle_brush_actions function in jschart
- 87c7647 Update the mouse coordinate display to support when the chart is timeseries
- 583ef9e Fixup timezone and time formatting support, defaulting to UTC
- 9f0a3a7 Update jschart to use a dynamic x-axis label showing the (zoomed) time range when the chart is timeseries
- 3534125 Update GenData to use jschart
- bb36819 Update jschart to be compatible with GenData chart type specifications
- 3b3889f Update the jschart highlight functions to have more descriptive names
- 1f354a7 Update D3 Queue initialization to match d3-queue code available via npm
- 28d51b9 Add support for saveSvgAsPng to jschart
- 3029052 Add support for specifying whether a jschart is a XY plot or timeseries
- 247216b Remove the jschart assertion that the x-axis domain should have a minimum=0 unless otherwise specified
- 72a42e9 Add support for loading CSV data files into jschart
- 785b27c Update jschart.js to dynamically build the summary table at runtime
- c8b781a Initial commit of jschart files pulled from LPCPU
- 7224a5a Clean up the list file.
- ef3f12b Fix the COPR repo URL.
- 6a1e74f Store cron job script logs in the local file system.
- fc9d61d modified oc scrit -> fixed typo -> if decided to start too, instructed to install 'expect' package - necessary for unbuffer
- 02eb062 Fix the calls to check_installed_rpm in all the benchmarks.
- 6c48dbe Script rename: metadata-log --> pbench-metadata-log
- 2b8b991 Modify the sar script (and its relatives) to handle user-defined options.
