#! /bin/bash
# -*- mode: shell-script -*-

# deploy script for pbench background tasks
# depends on ./config/deploy.conf
# Dependcency: configtools

while getopts dh x ;do
    case $x in
        d)
            debug=1
            ;;
        h)
            help=1
            ;;
    esac
done

if [[ $help == 1 ]] ;then
    echo "Usage: deploy [-dh]"
    exit 0
fi

if [[ $debug == 1 ]] ;then
    rsync="echo /usr/bin/rsync"
    ssh="echo /usr/bin/ssh"
else
    rsync=/usr/bin/rsync
    ssh=/usr/bin/ssh
fi

# override for debugging, comment out for production


opts=$SHELLOPTS
case $opts in
    *xtrace*)
        dir=$(dirname $(which $0))
        PROG=$(basename $(which $0))
        ;;
    *)
        dir=$(dirname $0)
        PROG=$(basename $0)
        ;;
esac

export CONFIG=$dir/config/deploy.conf

if [ ! -f $CONFIG ] ;then
   echo "$prog: required config file $CONFIG does not exist" > /dev/stdout
   exit 1
fi

PATH=/opt/configtools/bin:$PATH

if which getconf.py > /dev/null 2>&1 ;then
    :
else
    echo "The configtools package must be installed."
    exit 2
fi

TMP=/tmp/deploy-bgtasks.$$
mkdir -p $TMP
trap "rm -rf $TMP" EXIT INT QUIT

function do_scripts {
    role=$1
    user=$2
    host=$3
    shift 3
    scripts=$*

    scriptdir=$dir/$(getconf.py script-dir deploy)
    files=""
    for script in $scripts ;do
        if [ -f $scriptdir/$script ] ;then
            files="$files $scriptdir/$script"
        fi
    done
    $rsync -avz $files $user@$host:$(getconf.py deploy-script-dir $role)
}

# refactor
function do_libs {
    role=$1
    user=$2
    host=$3
    shift 3
    libs=$*

    libdir=$dir/$(getconf.py lib-dir deploy)
    files=""
    for lib in $libs ;do
        if [ -e $libdir/$lib ] ;then
            files="$files $libdir/$lib"
        fi
    done
    $rsync -avz $files $user@$host:$(getconf.py deploy-lib-dir $host deploy)
}

function do_crontab {
    role=$1
    user=$2
    host=$3
    crontabs=$4

    # make sure the directory exists
    $ssh $user@$host mkdir -p $(getconf.py deploy-crontab-dir $role deploy)
    # copy the file
    $rsync -avz $crontabs $user@$host:$(getconf.py deploy-crontab-dir $host deploy)/crontab
    # refresh cron
    $ssh $user@$host crontab $(getconf.py deploy-crontab-dir $role deploy)/crontab
}

function deploy_host {
    role=$1
    host=$(getconf.py host $role)

    user=$(getconf.py user $role deploy)
    tasks=$(getconf.py -l tasks $role)

    hostscripts=""
    if [ ! -z "$tasks" ] ;then
        # general scripts
        hostscripts=$(getconf.py -l scripts deploy)
        hostscripts="$hostscripts $(getconf.py -l scripts $role)"
    fi
    # scripts and libs are concatenated and passed as arguments
    scripts="$hostscripts"
    libs=""
    # Don't pass crontab entries as arguments: newlines are mangled.
    # Use a file instead.
    crontabs=$TMP/crontab.$host
    # make sure the file starts out empty.
    > $crontabs
    for task in $tasks ;do
        # avoid introducing unnecessary spaces: the -z below won't work.
        if [ -z "$scripts" ] ;then
            scripts="$(getconf.py -l scripts $task)"
        else
            scripts="$scripts $(getconf.py -l scripts $task)"
        fi
        
        if [ -z "$libs" ] ;then
            libs="$(getconf.py -l libs $task)"
        else
            libs="$libs $(getconf.py -l libs $task)"
        fi
        
        getconf.py -l crontab $task >> $crontabs
    done

    if [ ! -z "$scripts" ] ;then
        do_scripts $role $user $host $scripts
    fi
    if [ ! -z "$libs" ] ;then
        do_libs $role $user $host $libs
    fi
    if [ -s "$crontabs" ] ;then
        do_crontab $role $user $host "$crontabs"
    fi
}

roles=$(getconf.py -l roles deploy)
for role in $roles ;do
    deploy_host $role
done

exit 0
