#!/bin/bash

echo "This is the uperf client launcher"
echo "args: $@"

uperf_vars=""
while [ ! -z "$1" ]; do
	arg=`echo $1 | awk -F= '{print $1}' | sed -e s/^--// -e 's/-/_/g'`
	val=`echo $1 | awk -F= '{print $2}'`
	if [ $arg == "message_size" ]; then
		uperf_vars="$uperf_vars wsize=$val rsize=$val"
	elif [ $arg == "servers" -o $arg == "remotehost" ]; then
		let field=$pbench_count+1
		host=`echo $val | cut -d, -f$field`
		uperf_vars="$uperf_vars remotehost=$host"
	else
		uperf_vars="$uperf_vars $arg=$val"
	fi
	shift
done
uperf_vars=`echo $uperf_vars | sed -e 's/^ //'`
port=`echo "20000 + 3 * $pbench_count" | bc`
echo "uperf_vars: [$uperf_vars]"
printf "%s\n" "#!/bin/bash" >uperf-client.cmd
printf "%s %s\n" "$uperf_vars" "/usr/local/bin/uperf -v -m ./uperf.xml -x -a -i 1 -P $port >uperf-client-stdout.txt 2>uperf-client-stderr.txt" >>uperf-client.cmd
chmod +x ./uperf-client.cmd
./uperf-client.cmd
