#!/usr/bin/python3
# -*- mode: python -*-

"""Place-holder "node-exporter" persistent tool, providing a help message
like the other existing transient tools, and issuing a warning indicating
this script is not actually executed directly.

The actual tool invocation is handled directly by the Tool Meister code.
This is associated with the Prometheus collector run by the Tool Data Sink.
"""

import sys

if len(sys.argv) == 2 and sys.argv[1] == "--help":
    help = """Options:

--interval=# (number of seconds between collections)

For more information on the 'node_exporter' tool, please visit the GitHub Project:
\thttps://github.com/prometheus/node_exporter
"""
    print(help)
    sys.exit(0)

print(
    "This script is a place-holder only; please run it with '--help' for"
    " info on registering the tool.",
    file=sys.stderr,
)
sys.exit(1)
