#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; tab-width: 8 -*-

PROG="$(basename ${0})"

devices="${@}"
if [[ -z "${devices}" ]]; then
	printf "%s: missing required 'devices' argument\n" "${PROG}" >&2
	exit 1
fi

command -v blktrace > /dev/null
if [[ ${?} -ne 0 ]]; then
	printf "%s: missing required 'blktrace' command\n" "${PROG}" >&2
	exit 1
fi

blktrace ${devices}
