#!/bin/bash

interval=$1
file=$2

cat /dev/null >$file
sysfs_spinlock_dir=/sys/kernel/debug/kvm/spinlocks
while true; do
	echo "timestamp: `date +%s.%N`" >>$file
	for i in `/bin/ls $sysfs_spinlock_dir | grep -v "histo_blocked" | grep -v "zero_stats"`; do
		echo $i: `cat $sysfs_spinlock_dir/$i` >>$file
	done
	echo >>$file
	sleep $interval
done
popd >/dev/null
