#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; tab-width: 8 -*-

PROG="$(basename ${0})"

tool_output_dir="${1}"
if [[ ! -d "${tool_output_dir}" ]]; then
    printf -- "%s: invalid tool output directory, '%s'\n" "${PROG}" "${tool_output_dir}" >&2
    exit 1
fi

interval="${2}"
if [[ -z "${interval}" ]]; then
	printf -- "%s: missing required 'interval' argument\n" "${PROG}" >&2
	exit 1
fi

options="${3}"

default_options="-A"

if [[ -z "${_tool_bin}" ]]; then
	_tool_bin="/usr/local/bin/sar"
fi
if [[ ! -x ${_tool_bin} ]]; then
	printf -- "%s: missing required '${_tool_bin}' command\n" "${PROG}" >&2
	exit 1
fi

${_tool_bin} ${default_options} ${options} -o ${tool_output_dir}/sar.data ${interval}
