#!/bin/bash

# This script runs the legacy unit tests for the Agent and the Server.
#
# NOTE:  Before invoking this script, the various bits of Python setup should
#        have been performed, e.g., via `source jenkins/python-setup.sh`.

prog="$(basename "${0}")"
progdir="$(realpath -e $(dirname "${0}")/..)"

# List of environments to run.
envs="agent/tool-scripts/datalog agent/tool-scripts/postprocess agent/tool-scripts agent/util-scripts agent/bench-scripts server/bin"

for env in ${envs}; do
    if [[ ! -x ${progdir}/${env}/unittests ]]; then
        printf -- "Ignoring unrecognized environment, ${env}\n" >&2
        (( errors++ ))
        continue
    fi

    printf -- "+++ Env ${name} Tests +++\n\n"
    ${progdir}/${env}/unittests
    status=${?}
    printf -- "\n--- Env ${name} Tests ($status) ---\n"

    if [[ ${status} -ne 0 ]]; then
        printf -- "#--- (FAILED: %d)\n" "${status}"
        (( errors++ ))
    else
        printf -- "#--- (SUCCESS)\n"
    fi
    printf -- "\n\n"
done

if [[ ${errors} -gt 0 ]]; then
    printf -- "\n\nTests failed! (%d errors)\n" ${errors}
    exit 1
else
    printf -- "\n\nTests succeeded.\n"
    exit 0
fi
