#!/bin/bash

prog="$(basename "${0}")"
progdir="$(realpath -e $(dirname "${0}")/..)"

_prefix="${1}"

pip3 install --no-cache-dir --prefix="${_prefix}" -r ${progdir}/agent/requirements.txt -r ${progdir}/server/requirements.txt -r ${progdir}/agent/test-requirements.txt -r ${progdir}/server/test-requirements.txt

_pdir=${_prefix}/bin
if [[ ":${PATH:-}:" != *":${_pdir}:"* ]]; then
    export PATH=${_pdir}${PATH:+:${PATH}}
fi

_pdir="$(ls -1d ${_prefix}/lib/python3.*/site-packages)"
if [[ ":${PYTHONPATH:-}:" != *":${_pdir}:"* ]]; then
    export PYTHONPATH=${_pdir}${PYTHONPATH:+:${PYTHONPATH}}
fi

_pdir="$(head -n 1 ${_prefix}/lib/python3.*/site-packages/pbench.egg-link)"
if [[ ":${PYTHONPATH:-}:" != *":${_pdir}:"* ]]; then
    export PYTHONPATH=${_pdir}${PYTHONPATH:+:${PYTHONPATH}}
fi

printf -- "lint check ... \n"
tox -e lint
print -- "python3 check ..\n"
tox -e py3
