#!/bin/bash

prog="$(basename "${0}")"
progdir="$(realpath -e $(dirname "${0}")/..)"

source $(dirname "${0}")/python-setup.sh

printf -- "black --check ...\n"
black --check .
printf -- "\nflake8 --verbose ...\n"
flake8 --verbose .
printf -- "\n"
pytest ./lib/pbench/test/unit/common ./lib/pbench/test/unit/agent ./lib/pbench/test/unit/server ./lib/pbench/test/functional
