#!/bin/bash
set -o errexit

export PB_INTERNAL_CONTAINER_REG=images.paas.redhat.com
export PB_ORG_NAME=pbench
export PB_SERVER_IMAGE_NAME=pbench-server-ci
export PB_SERVER_IMAGE_TAG=${USER}
export PB_SERVER_IMAGE="${PB_INTERNAL_CONTAINER_REG}/${PB_ORG_NAME}/${PB_SERVER_IMAGE_NAME}"
export PB_POD_NAME=pbench-in-a-can
export PB_DASHBOARD_DIR=$(pwd)/dashboard/build

make -C server/rpm clean rpm

#buildah login -u='$app' -p="${__LOGIN_SECRET__}" ${PB_INTERNAL_CONTAINER_REG}

RPM_PATH=${HOME}/rpmbuild/RPMS/noarch/pbench-server-*.rpm bash -ex ./server/pbenchinacan/container-build-ci.sh
buildah push localhost/${PB_SERVER_IMAGE_NAME}:${PB_SERVER_IMAGE_TAG} ${PB_SERVER_IMAGE}:${PB_SERVER_IMAGE_TAG}

jenkins/run-server-func-tests
