#!/bin/bash -e

# Build the Pbench Server RPM and container, and run functional tests locally.
# Requires a Fedora, CentOS, or RHEL environment to run.

# Build the pbench-server RPM locally, then build the containers locally, and
# then run the functional tests against the locally built CI container image.
export PB_SERVER_IMAGE_NAME=pbench-server

# We use the current user name as the tag to avoid any conflict with what the CI
# environment does.
export PB_SERVER_IMAGE_TAG=${USER}

# We use the image pull policy of `never` here to ensure our locally built image
# is used by the pod.
export PB_SERVER_IMAGE_PULL_POLICY=never

# Create an RPM from the current source tree.
make -C server/rpm clean rpm

source /etc/os-release

# Build the canned Pbench Server container from the RPM built above.
BASE_IMAGE=${ID}:${VERSION_ID} RPM_PATH=${HOME}/rpmbuild/RPMS/noarch/pbench-server-*.rpm server/pbenchinacan/container-build.sh

# Run the functional tests using the locally built image.
jenkins/run-server-func-tests
