#!/bin/bash -e

# Build the pbench-server RPM locally, then build the containers locally, and
# then run the fuctional tests against the locally built CI container image.

export PB_CONTAINER_REG=images.paas.redhat.com
export PB_ORG_NAME=pbench
export PB_SERVER_IMAGE_NAME=pbench-server
export PB_SERVER_IMAGE_TAG=${USER}
export PB_SERVER_IMAGE_PULL_POLICY=Never

# We explicit set WORKSPACE_TMP so that RPM build (which uses a container image)
# will store the resulting RPM in that work space temporary directory so we can
# reference it when building the container images.
export WORKSPACE_TMP=/var/tmp/${USER}/runlocal
mkdir -p /var/tmp/${USER}
rm -rf ${WORKSPACE_TMP}
mkdir ${WORKSPACE_TMP}

# Create a RHEL 9 RPM from the current source tree.
make -C server/rpm clean rhel-9-rpm

# Build the CI container from the RPM built above.
RPM_PATH=${WORKSPACE_TMP}/rpmbuild/RPMS/noarch/pbench-server-*.rpm bash -ex ./server/pbenchinacan/container-build.sh

# Run the functional tests using the locally built image.
jenkins/run-server-func-tests
