#!/bin/bash -e

# Alembic command expects to run in our database directory.
cd lib/pbench/server/database

# Our env requires a pbench-server config file.
export _PBENCH_SERVER_CONFIG=$(pwd)/pbench-server.cfg

# Had to run the command below before I could create the initial tables.
#alembic stamp head

# Then I could create the initial migration against an empty database.
#alembic revision --autogenerate -m "Initial tables"
