---
# we need the top-level pbench directory on each server
# in order to create a bunch of links in the httpd doc root
# (see the last task in this file). We need to ask the server
# for it because it may vary by server.

- name: links in doc root to various pbench directories
  file:
    src: "{{ pbench_dir }}/public_html/{{ item }}"
    path: "{{ httpd_document_root_dir }}/{{ item }}"
    state: link
  with_items:
    - incoming
    - results
    - users
    - static
  notify:
    - restart apache


