---
- name: uninstall pbench-server
  hosts: servers
  remote_user: root
  become: yes
  become_user: root

  vars:
    package_state: "absent"

  roles:
    - pbench-server-deactivate-crontab
    - pbench-server-deactivate-results-host-info
    - pbench-server-uninstall
    - pbench-server-deps
