---
# ASSUMPTION: any necessary boostrapping has already been done.
- name: install server deps
  hosts: servers
  remote_user: root
  become: yes
  become_user: root

  roles:
    - pbench-server-deps

