#!/bin/bash

NCPUS=${1}
if [[ -z "${NCPUS}" ]]; then
    echo "Missing number of CPUs to use" >&2
    exit 1
fi

TARGETDIR=${2}
if [[ -z "${TARGETDIR}" ]]; then
    echo "Missing target directory argument" >&2
    exit 1
fi

WORKDIR=/var/tmp/bitrot-detect
mkdir -p ${WORKDIR}

# Clean up previous run.
rm -f ${WORKDIR}/tbs.md5-*

# We "find" all the controller directories and process them in alphabetical
# order.
find ${TARGETDIR} -maxdepth 1 -mindepth 1 -type d -printf '%P\n' | sort | while read ctrl; do
    find ${TARGETDIR}/${ctrl} -maxdepth 1 -mindepth 1 -type f -name '*.tar.xz' | while read tb; do
        # Detect empty tar balls
        if [[ ! -s ${tb} ]]; then
            printf -- "Empty tar ball found: %s\n" "${tb}" >&2
            continue
        fi
        _md5=${tb}.md5
        if [[ ! -f ${_md5} ]]; then
            printf -- "MD5 file for tar ball missing: %s\n" "${tb}" >&2
        elif [[ ! -s ${_md5} ]]; then
            printf -- "Empty tar ball MD5 file found: %s\n" "${_md5}" >&2
        else
            # For each controller, we read all the .md5 file contents re-
            # emitting those contents with a file name that contains the full
            # path.
            awk "{ print \$1, \"${TARGETDIR}/${ctrl}/\" \$2 }" ${_md5}
        fi
    done
    # All the output is captured into one file so that the requested
    # concurrency can be provided below.
done > ${WORKDIR}/tbs.md5 2> ${WORKDIR}/tbs.err

cat ${WORKDIR}/tbs.err; echo ""

# We use the `--number=r/N` form so that all the workers below will chew
# through the list together in alphabetical order. This makes it convenient
# for an observer to understand how far along the bit-rot detection process
# has progressed.
split --number=r/${NCPUS} ${WORKDIR}/tbs.md5 ${WORKDIR}/tbs.md5-

for i in ${WORKDIR}/tbs.md5-*; do
    md5sum --check ${i} > ${i}.out 2> ${i}.err &
done
wait

cat ${WORKDIR}/tbs.md5-*.err; echo ""

grep -v "OK" ${WORKDIR}/tbs.md5-*.out

exit 0
