#!/bin/bash

cd $(dirname ${0})
yarn install --network-timeout 1000000
if [[ ${?} -ne 0 ]]; then
  echo "yarn install failed!" >&2
  exit 1
fi
yarn lint
if [[ ${?} -ne 0 ]]; then
  echo "yarn lint failed!" >&2
  exit 1
fi
yarn test
if [[ ${?} -ne 0 ]]; then
  echo "yarn unit tests failed!" >&2
  exit 1
fi
exit 0
