# {{ distro }} pbench-agent tools image
FROM quay.io/pbench/pbench-agent-base-{{ distro }}:latest

# Install all the RPMs required for tools.
#
# FIXME: this is not exhaustive, it does not include RPMs to support
#        Kubernetes or RHV environments.
RUN {% if distro == 'centos-7' %}yum{% else %}dnf{% endif %} install -y {% if distro == 'centos-8' %}--enablerepo PowerTools {% endif %}--enablerepo copr-pbench pbench-sysstat perf blktrace bpftrace numactl pcp-system-tools strace kernel-tools tcpdump && \
    {% if distro == 'centos-7' %}yum{% else %}dnf{% endif %} -y clean all && \
    rm -rf /var/cache/yum
