#! /bin/bash
#
# This script is a wrapper to facilitate the invocation of a Pbench Agent
# command using a containerized deployment of the Pbench Agent. Simply prefix
# a Pbench Agent command line with the path to this script to run it inside a
# container, without needing to install the Agent on the host system.
#
# Invocation options are provided as environment variables:
#    PB_AGENT_IMAGE_NAME: the full image name for the containerized Pbench Agent
#    PB_AGENT_RUN_DIR: the directory for use as the Pbench Agent "run directory"
#    PB_AGENT_CA: a CA bundle to verify Pbench Server PUTs
#    PB_AGENT_PODMAN_OPTIONS: Additional options to be supplied to Podman run
#
# In all cases, reasonable defaults are supplied if the environment variables
# are not defined.
#
# This script manages a persistent host Pbench Agent "run directory", which
# defaults to /var/tmp/{USER}/pbench-agent/run, and maps that directory into
# the container so that multiple runs can be generated and uploaded at once.
#
# To upload results to a Pbench Server, use this script to execute the
# pbench-results-move command within the container, specifying either --relay
# with the address of a Pbench Relay Server, or --server with the address of a
# Pbench Server and --token to specify a Pbench Server API key for user
# authentication.
#
# To use a server with a certificate signed by the Pbench development CA bundle
# define the environment variable PB_AGENT_CA to cause the CA to be mapped into
# the container and defined using REQUESTS_CA_BUNDLE:
#
#  PB_AGENT_CA=server/pbenchinacan/etc/pki/tls/certs/pbench_CA.crt \
#    contrib/containerized-pbench/pbench pbench-results-move \
#      --server https://<server>:8443 --token <api-token>

image_name=${PB_AGENT_IMAGE_NAME:-quay.io/pbench/pbench-agent-all-centos-8:main}
pbench_run_dir=${PB_AGENT_RUN_DIR:-/var/tmp/${USER}/pbench-agent/run}
ca=${PB_AGENT_CA:-${REQUESTS_CA_BUNDLE}}
if [[ ${ca} ]]; then
    pbench_ca=$(realpath ${ca})  # expand path outside container
fi
container_ca=/etc/pki/tls/certs/pbench_CA.crt  # path inside container
other_options=${PB_AGENT_PODMAN_OPTIONS}

if [[ $# == 0 || $1 == "help" || $1 == "-h" || $1 == "--help" ]]; then
    echo "Usage:  ${0} <Pbench Agent Command> [<arg>...]" >&2
    exit 2
fi

mkdir -p ${pbench_run_dir}
if [[ -f "${pbench_ca}" ]]; then
    other_options="-v ${pbench_ca}:${container_ca}:z ${other_options}"
    other_options="-e REQUESTS_CA_BUNDLE=${container_ca} ${other_options}"
fi
other_options="--security-opt=label=disable -v ${pbench_run_dir}:/var/lib/pbench-agent:z ${other_options}"

podman run \
    -it \
    --rm \
    --network host \
    --name pbench-agent \
    ${other_options} \
    ${image_name} "${@}"
