#! /bin/bash -xe
#
# This script provides a demonstration of the contrib/containerized-pbench/pbench
# wrapper script.
#

#+
# Set up a few things to make life simpler.  Typically, these would already be
# set in the users environment (e.g., the `pbench` command alias would be done
# by the user's login script; we wouldn't need the `shopt` command if these
# commands were being run interactively; and, we only need `PB_AGENT_IMAGE_NAME`
# here because we're not using the default image).
#-
shopt -s expand_aliases
alias pbench="$(git rev-parse --show-toplevel)"/contrib/containerized-pbench/pbench

FIOTEST=${PWD}/fiotest
export PB_AGENT_PODMAN_OPTIONS="--pull newer -v ${FIOTEST}:/fiotest:z"
export PB_AGENT_IMAGE_NAME=quay.io/pbench/pbench-agent-all-fedora-36:main

mkdir -p "${FIOTEST}"

#+
# Run the demo!
#-
pbench pbench-generate-token --output=/var/lib/pbench-agent/.token
pbench pbench-register-tool-set light
pbench pbench-list-tools
pbench pbench-user-benchmark --config example-workload -- \
    fio --directory=/fiotest --name fio_test_file --direct=1 --rw=randread \
        --bs=16k --size=100M --numjobs=8 --time_based --runtime=5s \
        --group_reporting --norandommap
# Note that the token file location below is evaluated -outside- the container,
# unlike in the pbench-generate-token command above.
pbench pbench-results-move --token="$(< /var/tmp/"${USER}"/pbench-agent/run/.token)"
