---
- name: Run the role that expunges the yum cache completely
  ansible.builtin.import_role:
    name: pbench_clean_yum_cache

- name: Install RPMs
  ansible.builtin.package:
    name:
      - pbench-agent
      - pbench-sysstat
    state: latest
