---
# Install pbench.repo
- name: ensure we have the pbench.repo file properly in place
  template:
    src: etc/yum.repos.d/pbench.repo.j2
    dest: /etc/yum.repos.d/pbench.repo
    owner: root
    group: root
    mode: 0644

