#!/bin/bash

echo "$0 $*" >> $_testlog

# Mock fio command behaviors.
if [[ "${1%%=*}" == "--client" ]]; then 
	client_file=${1##*=}
	for line in $(< ${client_file}); do
		ip_name="${line%%,*}"
		client="${ip_name#*:}"
		if [[ "${client%%.*}" == "hist" ]]; then 
			# When we are mocking out a benchmark command for pbench-fio,
			# for each client which begins with "hist" create an empty
			# fio latency histogram log file so that the invocation of
			# our latency visualizations can be exercised.
			touch ./fio_clat_hist.empty.log.${client}
		fi
	done
elif [[ "${1}" == "--version" ]]; then 
	echo "fio-${_BM_FIO_VER:-3.42}"
	exit 0
fi

exit ${_BM_FIO_STS:-0}
