#!/bin/bash

cmd="$0 $*"
echo "$cmd" >> $_testlog

# make pid 123463 unkillable, except on KILL
pid=""
case $1 in
    -s)
        signal=$2
        pid=$3
        ;;
    *)
        signal=NONE
        pid=$1
        shift
        ;;
esac

echo $signal/$pid >> $_testlog
if [ "$signal" == KILL ] ;then

    echo "$cmd" exited with 0 >> $_testlog
    exit 0
fi

if [ "$pid" == 123463 ] ;then
    echo "$cmd" exited with 1 >> $_testlog
    exit 1
fi

echo "$cmd" exited with 0 >> $_testlog
exit 0
