#!/bin/bash

if [[ -z "${*}" ]]; then
    echo "${0}" >> ${_testlog}
else
    echo "${0} ${*}" >> ${_testlog}
fi

prog="$(basename "${0}")"
args=( "${@}" )
lastidx=$((${#args[@]} - 1))
# avoid "bad array subscript" error
if [[ "${lastidx}" -lt 0 ]] ;then
    exit 0
fi

last=${args[${lastidx}]}
if [[ "${prog}" == "pbench-metadata-log" && "${last}" == "beg" ]]; then
    echo [pbench] > ${benchmark_run_dir}/metadata.log
elif [[ "${prog}" == "cat" && "${args[0]}" == "/proc/cmdline" ]]; then
    echo "intel_iommu=on"
fi
exit 0
