#!/bin/bash

echo "$0 $*" >> $_testlog

while true ;do
    case $1 in
        -o)
            shift 2
            ;;
        -n)
            shift 1
            ;;
        *)
            break
            ;;
    esac
done
remote=$1

if [[ "$2" == "netstat" && "$3" == "-tlnp" ]]; then
    echo "tcp        0      0 0.0.0.0:21000               0.0.0.0:*                   LISTEN      5830/uperf"
fi

if [[ "$2" == "hostname" && "$3" == "-s" ]]; then
    echo "$remote"
fi

if [[ "$remote" == "fubar" ]] ;then
    exit 255
else
    exit 0
fi
