---
dependencies: []

galaxy_info:
  role_name: pbench_clean_yum_cache
  author: The Pbench team
  description: Role to clean the yum cache.
  license: "license(GPL-3.0-or-later)"
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - all
    - name: RHEL
      versions:
        - 7
        - 8
    - name: CentOS
      versions:
        - 7
        - 8
  galaxy_tags:
    - pbench
