#!/bin/bash

prog="$(basename "${0}")"
args=( "${@}" )
lastidx=$((${#args[@]} - 1))
# avoid "bad array subscript" error
if [[ "${lastidx}" -lt 0 ]] ;then
    exit 0
fi

if [[ "${prog}" == "cp" && "${args[1]}" == "/etc/ssh/ssh_config.d" ]]; then
    if [[ -z "${*}" ]]; then
        echo "${0}" >> ${_testlog}
    else
        echo "${0} ${*}" >> ${_testlog}
    fi
    mkdir "${args[2]}/ssh_config.d"
    exit ${?} 
fi
${_real_cp} ${*}
