#!/usr/bin/env python3

import os
import sys
import time

_prog = os.path.basename(sys.argv[0])

with open(os.environ["_testlog"], "a") as tfp, open(f"{_prog}.file", "a+") as ofp:
    args = " ".join(sys.argv)
    line = f"{args}\n"
    tfp.write(line)
    ofp.write(line)

time.sleep(9999)

sys.exit(0)
