#!/usr/bin/env python3

import os
import sys
import time

from pathlib import Path

args = " ".join(sys.argv)
with open(os.environ["_testlog"], "a") as ofp:
    ofp.write(f"{args}\n")

_prog = os.path.basename(sys.argv[0])

# Create a file in the current working directory to mark its use so we can
# ensure we don't run programs where they were not supposed to run.
if _prog not in ("pbench-tool-meister-client", "yum", "scp"):
    with open(f"{_prog}.file", "a+") as ofp:
        ofp.write(f"{args}\n")

_sleepers = ["dcgm-exporter", "jaeger-agent", "jaeger-all-in-one", "node_exporter", "pmcd", "prometheus"]

if _prog == "pbench-sysinfo-dump":
    tgtdir = Path(sys.argv[1])
    sysinfo = sys.argv[2]
    (tgtdir / "contents.lis").write_text(sysinfo)
elif _prog == "prometheus" and sys.argv[1] != "run":
    pass
elif _prog in _sleepers:
    time.sleep(9999)

sys.exit(0)
