#!/usr/bin/env python3

import os
import sys
import time

with open(os.environ["_testlog"], "a") as ofp:
    args = " ".join(sys.argv)
    ofp.write(f"{args}\n")

if sys.argv[1] == "run":
    time.sleep(9999)

sys.exit(0)
