#!/bin/bash

echo "${0} ${*}" >> ${_testlog}

while true ;do
    case ${1} in
        -i)
            shift 2
            ;;
        -o)
            shift 2
            ;;
        -n)
            shift 1
            ;;
        *)
            break
            ;;
    esac
done
remote=${1}
shift

if [[ "${1}" == "hostname" && "${2}" == "-s" ]]; then
    echo "${remote}"
    exit_code=0
elif [[ "$(basename -- "${1}")" == "pbench-tool-meister-remote" ]]; then
    _dir=$(dirname ${0})
    _pbench_full_hostname="${remote}" _pbench_hostname="${remote}" _tool_bin=${_dir}/mpstat ${1} localhost "${3}" "${4}"
    exit_code=$?
fi

exit ${exit_code}
