#!/bin/bash
# Test require-rpm via a series of simple invocations

# The way we verify the behavior of require-rpm itself is by mocking out the
# behavior of `rpm` and `rpmdev-vercmp` to behave the way we want.  The name
# of the RPM encodes the behavior.

_tmp=$(dirname "${_testout}")/tmp
function _cleanup {
    rm -rf ${_tmp}
}
trap _cleanup INT QUIT TERM EXIT
mkdir ${_tmp}
if [[ ${?} -ne 0 ]]; then
    printf -- "test-require-rpm: failed to create temporary directory, %s\n" "${_tmp}" >&2
    exit 1
fi

function run_req_rpm {
    require-rpm ${*} > ${_tmp}/std.out 2> ${_tmp}/std.err
    echo "require-rpm ${*} --> ${?}"
    echo "+++ stdout"
    cat ${_tmp}/std.out
    echo "--- stdout"
    echo "+++ stderr"
    cat ${_tmp}/std.err
    echo "--- stderr"
    rm -f ${_tmp}/std.{out,err}
}

# Verify no-arguments
run_req_rpm

# Verify one argument, RPM not found
run_req_rpm not-found

# Verify one argument, RPM found
run_req_rpm found

# Verify two arguments, RPM not found with that version
run_req_rpm not-found 1.0.0

# Verify two arguments, RPM found with that version
run_req_rpm found 1.0.0

# Verify three arguments, 3rd argument not recognized
run_req_rpm found 1.0.0 foo

# Verify three arguments, 3rd argument is "any", not found
run_req_rpm not-found 1.0.0 any
# Verify three arguments, 3rd argument is "any", found
run_req_rpm found 1.0.0 any

# Verify three arguments, 3rd argument is "equ", not equal
run_req_rpm not-equal 1.0.0 equ
# Verify three arguments, 3rd argument is "equ", equal
run_req_rpm equal 1.0.0 equ

# Verify three arguments, 3rd argument is "gte", not greater or equal
run_req_rpm not-greater-equal 1.0.0 gte
# Verify three arguments, 3rd argument is "gte", greater or equal
run_req_rpm greater-equal 1.0.0 gte

# Verify three arguments, 3rd argument is "gtr", not greater
run_req_rpm not-greater 1.0.0 gtr
# Verify three arguments, 3rd argument is "gtr", greater
run_req_rpm greater 1.0.0 gtr

# Verify 3 arguments, multiple RPM version, "equ", not equal
run_req_rpm not-equal-mult 1.0.0 equ
# Verify 3 arguments, multiple RPM version, "equ", equal
run_req_rpm equal-mult 1.0.0 equ

exit 0
