# Workflow to build and deploy GitHub Pages
name: Build & Deploy content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: ["docs/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  
  # This job will build readthedocs page into 'docs/' sub-dir
  build:
    runs-on: ubuntu-latest
    defaults:
      # set working-directory to docs/ for all run commands
      run:
        shell: bash
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies and Build with readthedocs site
        run: |
          pip install -r requirements.txt
          make html
      - name: copy static html content from _build dir to root docs dir
        run: cp -rf _build/html ./docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload docs dir
          path: 'docs/'
  
  # This job will deploy the pbench website.   
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

